import fs from 'node:fs/promises';import path from 'node:path';import {parseYaml} from './yaml.mjs';
export async function readConfig(file){const text=await fs.readFile(file,'utf8');return /\.json$/i.test(file)?JSON.parse(text):parseYaml(text);}
export function merge(...layers){const into=(a,b)=>{for(const [k,v] of Object.entries(b??{}))a[k]=v&&typeof v==='object'&&!Array.isArray(v)?into({...a[k]},v):v;return a;};return layers.reduce((a,b)=>into(a,b),{});}
export const SOURCE_MODES=['local','web','hybrid'];
export function canonicalSourceMode(mode){return ({'provided-only':'local',public:'web'})[mode]??mode;}
export function validateConfig(c){const allowed=['product-overview','competitor-analysis','user-insight','market-insight','product-strategy','product-planning','feature-proposal','executive-review'];if(!c.project?.name?.trim())throw new Error('缺少 project.name / 主题。');if(!allowed.includes(c.presentation?.type))throw new Error('不支持的 presentation.type。');if(!c.template?.id)throw new Error('未指定模板 template.id。');if(typeof c.research?.enabled!=='boolean')throw new Error('research.enabled 必须是 true/false。');const mode=canonicalSourceMode(c.research.source_mode);if(!SOURCE_MODES.includes(mode))throw new Error('research.source_mode 必须是 local、web 或 hybrid。');c.research.source_mode=mode;c.research.enabled=mode!=='local';c.visual={enabled:c.visual?.enabled!==false,acquisition:'screenshot',...c.visual};c.visual.acquisition='screenshot';if(['local','hybrid'].includes(mode)&&!(c.input_files??[]).length)throw new Error(`${mode==='local'?'本地':'本地+联网'}模式需要提供至少一个本地资料（--input 或 input_files）。`);if(c.research.enabled&&!c.research.competitors?.length&&!c.sources?.length)throw new Error('联网研究需要指定研究对象或经 Agent 核验的来源 URL。');return c;}
export function inferConfig(text,files=[]){const body=text.replace(/^\s*\/(?:CPGHBPPT|ppt)\b/i,'').trim();const found=(body.match(/Samsung|Sony|Hisense|TCL/gi)??[]);const competitors=[...new Set(found.map(x=>x[0].toUpperCase()+x.slice(1).toLowerCase()))];const noResearch=/不要\s*(?:Research|调研|研究)|只按照.*模板|已有.*内容|无需.*研究/i.test(body);const exact=/不要修改内容|不要改写|原文照搬/i.test(body);const type=/竞品|competitor/i.test(body)?'competitor-analysis':/NPS|用户洞察|用户调研/i.test(body)?'user-insight':/市场洞察/i.test(body)?'market-insight':/策略/i.test(body)?'product-strategy':/规划|Roadmap/i.test(body)?'product-planning':/功能方案/i.test(body)?'feature-proposal':'product-overview';
return {project:{name:(body.split(/[，。\n]/)[0]||'未命名演示').slice(0,65)},presentation:{type,purpose:body,language:'zh-CN',audience:'产品团队',brief:body},research:{enabled:!noResearch,competitors,markets:[],source_mode:files.length?'local':'web'},reasoning:{enabled:!exact,mode:exact?'minimal':'normal',content_rewrite:!exact},template:{id:'tcl-product'},visual:{enabled:true,acquisition:'screenshot'},output:{pptx:true,preview:true,sources:true},runtime:{offline:false,verbose:false},approval:{research_plan:false,storyline:false,final_preview:false},input_files:files};}
export async function loadLayers(root,projectFile){const org=await readConfig(path.join(root,'config/organization.yaml'));let user={};try{user=await readConfig(path.join(root,'config/user.yaml'));}catch(e){if(e.code!=='ENOENT')throw e;}return merge(org,user,projectFile?await readConfig(projectFile):{});}
