import fs from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';
import {inferConfig,validateConfig,merge} from '../config/index.mjs';import {workflow} from '../workflows/index.mjs';import {project,save,stage,sha} from './project.mjs';import {resolveTemplate} from './template.mjs';import {readInputs} from './input.mjs';import {dependencies} from './dependencies.mjs';import {skillRegistry} from './skills.mjs';import {runResearch} from '../../engine/research/index.mjs';import {makeEvidenceDeck} from '../../engine/reasoning/evidence-deck.mjs';import {createContentDeck} from '../output/content-deck.mjs';import {retrieveContext} from '../../engine/knowledge/index.mjs';import {evaluate} from '../../engine/critic/index.mjs';import {runVisualResearch,visualCoverage} from '../../engine/research/visual/index.mjs';
import {captureLocalVisuals} from './local-visuals.mjs';import {planDeckVisuals} from '../../engine/visual-planner/index.mjs';import {processVisualAssets} from '../../engine/assets/processor.mjs';import {planDeckLayouts} from '../../engine/layout/layout-engine.mjs';
const write=(f,v)=>fs.writeFile(f,typeof v==='string'?v:JSON.stringify(v,null,2));
async function invokeRenderer(root,template,artifacts,provider='python-pptx'){if(provider!=='python-pptx')throw new Error(`公开版仅支持 python-pptx Renderer：${provider}`);const d=await dependencies(root);const args=[path.join(root,'engine/bin/build-python.mjs'),'--deck',path.join(artifacts,'deck-plan.json'),'--slides',path.join(artifacts,'slide-specs.json'),'--template',template.master,'--output',path.join(artifacts,'render')];if(await fs.access(path.join(artifacts,'assets/asset-manifest.json')).then(()=>true,()=>false))args.push('--assets',path.join(artifacts,'assets/asset-manifest.json'));return await new Promise((resolve,reject)=>{const c=spawn(process.execPath,args,{cwd:root,env:{...process.env,...d}});let log='';c.stdout.on('data',x=>log+=x);c.stderr.on('data',x=>log+=x);c.on('error',reject);c.on('close',code=>code===0?resolve(log):reject(Object.assign(new Error(`Renderer 失败，详情见 logs/render.log（退出码 ${code}）`),{details:log})));}).catch(async e=>{throw e;});}
export async function build(root,input,{mode='build',verbose=false,approve=false}={}){const config=validateConfig(input);const wf=await workflow(root,config),template=await resolveTemplate(root,config.template.id);const p=await project(root,config);p.manifest.workflow_stages=wf.stages;p.manifest.skipped=wf.skipped;p.manifest.skills=(await skillRegistry(root)).filter(s=>wf.definition.skills.includes(s.id)).map(s=>({id:s.id,version:s.version}));p.manifest.template_version=template.manifest.version;await save(p);
  const folder=path.join(p.dir,'artifacts'),files=(config.input_files??[]).map(f=>path.resolve(root,f));const inputs=await readInputs(files);const inputSig=sha([config,inputs.map(x=>x.hash)]);const codeFingerprint=async files=>sha(await Promise.all(files.map(f=>fs.readFile(path.join(root,f),'utf8'))));p.manifest.status='UNDERSTANDING';await save(p);await stage(p,'UNDERSTANDING',inputSig,[path.join(folder,'01-brief.json')],()=>write(path.join(folder,'01-brief.json'),config));
  const researchEligible=config.research.enabled&&['web','hybrid','public'].includes(config.research.source_mode);let brief=null;
  if(researchEligible){const sample=JSON.parse(await fs.readFile(path.join(root,'tests/ai-picture/research-brief.json'),'utf8'));const known=['Samsung','Sony','Hisense'];if(/AI\s*Picture/i.test(config.project.name+' '+config.presentation.brief)&&known.every(b=>config.research.competitors.includes(b))&&!config.sources?.length){if(/最新|当前|2026|latest|most recent/i.test(config.presentation.brief??''))throw new Error('预置示例含 2025 Samsung 页面，不能冒充最新竞品研究。请由 Agent 联网核验最新官方 URL 和待核验短语。');brief={...sample,project_id:p.id};}else if(config.sources?.length){const brands=config.research.competitors?.length?config.research.competitors:[...new Set(config.sources.map(x=>x.brand).filter(Boolean))];brief={project_id:p.id,topic:config.presentation.brief,objective:config.presentation.purpose,brands,sources:config.sources};}else throw new Error('联网模式需要 Agent 先完成 Research，并提供经核验的公开来源 URL、声明和待核验短语。');}
  const knowledge=await retrieveContext(root,config,{enabled:config.runtime?.domain_packs!==false});const knowledgeFile=path.join(folder,'knowledge-context.json');await stage(p,'KNOWLEDGE_RETRIEVAL',sha(knowledge),[knowledgeFile],()=>write(knowledgeFile,knowledge));p.manifest.domain_packs=knowledge.packs.map(x=>({id:x.id,version:x.version,status:x.status}));p.manifest.selected_dimensions=knowledge.dimensions;p.manifest.knowledge_ids=knowledge.approved_knowledge.map(x=>x.id);const packSkillIds=new Set(knowledge.packs.flatMap(x=>x.skills));const selected=(await skillRegistry(root)).filter(s=>s.enabled&&!s.deprecated&&packSkillIds.has(s.id)&&(/ai.picture/i.test(config.project.name+' '+config.presentation.brief)?['picture-quality-competitor-analysis','ai-picture-analysis','ai-picture','ai-interaction','competitor-analysis','insight-extraction','opportunity-analysis','product-storyline'].includes(s.id):true));p.manifest.skills=[...new Map([...p.manifest.skills,...selected.map(s=>({id:s.id,version:s.version}))].map(x=>[x.id,x])).values()];await save(p);
  const planFile=path.join(folder,'02-research-plan.json');await stage(p,'PLANNING',sha([inputSig,wf]),[planFile],async()=>{const plan=researchEligible?(await import('../../engine/research/planner/index.mjs')).planResearch(brief):{stages:wf.stages,type:config.presentation.type,inputs:inputs.map(x=>x.name)};plan.domain_context={pack_ids:knowledge.packs.map(x=>x.id),selected_dimensions:knowledge.dimensions,knowledge_ids:knowledge.approved_knowledge.map(x=>x.id),use:'analysis_scope_not_source'};await write(planFile,plan);});p.manifest.status='PLANNING';await save(p);
  async function checkpoint(name){if(config.approval?.[name]&&!approve&&!p.manifest.approvals?.[name]){p.manifest.status=`WAITING_${name.toUpperCase()}`;p.manifest.checkpoint=name;await save(p);return true;}return false;}
  if(await checkpoint('research_plan'))return p;
  if(researchEligible){p.manifest.status='RESEARCHING';await save(p);const datasetPath=path.join(folder,'research/research-dataset.json');await stage(p,'RESEARCHING',sha([inputSig,new Date().toISOString().slice(0,10),await codeFingerprint(['engine/research/index.mjs','engine/research/evidence/index.mjs'])]),[datasetPath],async()=>{const dataset=await runResearch({brief,outputDir:folder,cacheDir:path.join(root,'cache/research')});if(dataset.sources.length<3||dataset.evidence.length<3)throw new Error('证据不足，已停止生成 PPT；请检查 research/issues.json 和 Research Summary。');});}
  const specsFile=path.join(folder,'slide-specs.json');const datasetPath=path.join(folder,'research/research-dataset.json');let dataset=null;if(researchEligible)dataset=JSON.parse(await fs.readFile(datasetPath,'utf8'));
  let visualManifest=null;if(researchEligible&&config.visual?.enabled!==false){const visualBrief=config.visual?.brief?JSON.parse(await fs.readFile(path.resolve(root,config.visual.brief),'utf8')):/AI\s*Picture/i.test(config.project.name+' '+config.presentation.brief)?JSON.parse(await fs.readFile(path.join(root,'tests/ai-picture/visual-brief.json'),'utf8')):{project_id:p.id,requests:(brief.sources??[]).map(source=>({brand:source.brand??source.title??'Source',product_page:source.url,feature_page:source.url,feature_text:source.probes?.[0]?.needle,screenshot_page:source.url,screenshot_text:source.probes?.[0]?.needle}))};const reviews=config.visual?.review_decisions?JSON.parse(await fs.readFile(path.resolve(root,config.visual.review_decisions),'utf8')):[];const manifestPath=path.join(folder,'assets/asset-manifest.json');p.manifest.status='VISUAL_RESEARCH';await save(p);await stage(p,'VISUAL_RESEARCH',sha([inputSig,sha(visualBrief),new Date().toISOString().slice(0,10),await codeFingerprint(['engine/research/visual/index.mjs','engine/research/visual/screenshot-capture/index.mjs','engine/research/browser/index.mjs'])]),[manifestPath],()=>runVisualResearch({dataset,brief:visualBrief,outputDir:folder,reviewDecisions:reviews}));visualManifest=JSON.parse(await fs.readFile(manifestPath,'utf8'));p.manifest.visual={found:visualManifest.coverage.summary.found,usable:visualManifest.coverage.summary.usable,required:visualManifest.coverage.summary.required};await save(p);}else if(!researchEligible&&config.visual?.enabled){visualManifest=await captureLocalVisuals(inputs,folder);p.manifest.visual={...visualManifest.coverage.summary};await save(p);}if(mode==='research'){p.manifest.status='COMPLETED_RESEARCH_ONLY';await save(p);return p;}if(researchEligible&&config.reasoning.enabled){p.manifest.status='ANALYZING';await stage(p,'ANALYZING',sha(dataset),[path.join(folder,'reasoning-context.json')],()=>write(path.join(folder,'reasoning-context.json'),{scope:'verified public pages and supplied local context',evidence_ids:dataset.evidence.map(e=>e.evidence_id),status:'bounded_readout',strategy:'not_generated'}));}p.manifest.status='STORYLINING';await save(p);
  let visualSignature=visualManifest?sha(visualManifest.assets.map(a=>[a.asset_id,a.content_hash,a.status,a.semantic_review])):'no-visual';const contentSig=sha([inputSig,sha(knowledge),visualSignature,researchEligible?sha(dataset):'local',await codeFingerprint([researchEligible?'engine/reasoning/evidence-deck.mjs':'app/output/content-deck.mjs'])]);await stage(p,'STORYLINING',contentSig,[specsFile],async()=>{if(researchEligible){const result=await makeEvidenceDeck(dataset,root,folder,{domainContext:knowledge,visualManifest,localInputs:config.research.source_mode==='hybrid'?inputs:[],config});if(visualManifest){for(const a of visualManifest.assets){a.related_slides=result.visualMatch.used.filter(u=>u.asset_id===a.asset_id).map(u=>u.slide_id);a.used=a.related_slides.length>0;}visualManifest.coverage=visualCoverage(result.visualPlan,visualManifest.assets);await write(path.join(folder,'assets/asset-manifest.json'),visualManifest);await write(path.join(folder,'assets/visual-coverage.json'),visualManifest.coverage);}await write(path.join(folder,'storyline.md'),`# ${config.project.name}\n\n${result.deck.slides.map((s,i)=>`${i+1}. ${s.key_message}`).join('\n')}\n`);}else await createContentDeck(root,config,inputs,folder,{visualManifest});});
  p.manifest.status='VISUAL_PLANNING';await save(p);
  const visualPlanFile=path.join(folder,'visual-plan.json');
  const rawSlides=JSON.parse(await fs.readFile(specsFile,'utf8'));
  const visualPlanningSig=sha([sha(rawSlides),visualSignature,await codeFingerprint(['engine/visual-planner/index.mjs'])]);
  await stage(p,'VISUAL_PLANNING',visualPlanningSig,[visualPlanFile],async()=>{
    const result=planDeckVisuals(rawSlides,{assets:visualManifest?.assets??[]});
    await write(visualPlanFile,{generated_at:new Date().toISOString(),agent:'visual-planner-v1',gate:result.gate,slides:result.plans});
    await write(specsFile,result.slides);
    await write(path.join(folder,'visual-decisions.json'),result.plans.map(plan=>({slide_id:plan.slide_id,visual_center:plan.visual_center,recommended_composition:plan.recommended_composition,primary_asset:plan.primary_asset,secondary_assets:plan.secondary_assets,reading_order:plan.reading_order,design_rationale:plan.design_rationale,status:plan.status,blockers:plan.blockers})));
    const deckFile=path.join(folder,'deck-plan.json'),deck=JSON.parse(await fs.readFile(deckFile,'utf8'));deck.renderer_entry_gate=result.gate;await write(deckFile,deck);
  });

  p.manifest.status='ASSET_PROCESSING';await save(p);
  const assetProcessingFile=path.join(folder,'asset-processing.json');
  await stage(p,'ASSET_PROCESSING',sha([visualPlanningSig,visualSignature,await codeFingerprint(['engine/assets/processor.mjs'])]),[assetProcessingFile],async()=>{
    const plannedSlides=JSON.parse(await fs.readFile(specsFile,'utf8'));
    const processed=await processVisualAssets(plannedSlides,visualManifest??{assets:[]},{outputDir:path.join(folder,'assets')});
    visualManifest=processed.manifest;
    const finalPlan=planDeckVisuals(processed.slides,{assets:visualManifest.assets??[]});
    await write(assetProcessingFile,{generated_at:new Date().toISOString(),status:processed.status,actions:processed.actions,visual_gate:finalPlan.gate});
    await write(specsFile,finalPlan.slides);
    await write(visualPlanFile,{generated_at:new Date().toISOString(),agent:'visual-planner-v1',gate:finalPlan.gate,slides:finalPlan.plans});
    if((visualManifest.assets??[]).length||await fs.access(path.join(folder,'assets/asset-manifest.json')).then(()=>true,()=>false))await write(path.join(folder,'assets/asset-manifest.json'),visualManifest);
    const deckFile=path.join(folder,'deck-plan.json'),deck=JSON.parse(await fs.readFile(deckFile,'utf8'));deck.renderer_entry_gate=finalPlan.gate;await write(deckFile,deck);
    if(finalPlan.gate.status!=='ready')throw new Error(`Visual Planner gate failed after Asset Processor: ${finalPlan.gate.blockers.map(item=>`${item.slide_id}:${item.code}`).join(', ')}`);
  });
  visualSignature=sha((visualManifest?.assets??[]).map(asset=>[asset.asset_id,asset.content_hash,asset.status,asset.semantic_review]));

  p.manifest.status='LAYOUT_PLANNING';await save(p);
  const layoutPlanFile=path.join(folder,'layout-plan.json');
  await stage(p,'LAYOUT_PLANNING',sha([sha(await fs.readFile(specsFile,'utf8')),await codeFingerprint(['engine/layout/layout-engine.mjs'])]),[layoutPlanFile],async()=>{
    const planned=planDeckLayouts(JSON.parse(await fs.readFile(specsFile,'utf8')));
    await write(layoutPlanFile,{generated_at:new Date().toISOString(),engine:'layout-engine-v1',gate:planned.gate,slides:planned.plans});
    await write(specsFile,planned.slides);
    if(planned.gate.status!=='ready')throw new Error(`Layout Engine gate failed: ${planned.gate.blockers.map(item=>`${item.slide_id}:${item.code}`).join(', ')}`);
  });

  if(mode==='outline'){p.manifest.status='COMPLETED_OUTLINE_ONLY';await save(p);return p;}if(await checkpoint('storyline'))return p;
  if(!config.output.pptx){p.manifest.status='COMPLETED_OUTLINE_ONLY';await save(p);return p;}
  p.manifest.status='RENDERING';await save(p);const final=path.join(folder,'render/AI-Picture.pptx'),slideHash=sha(await fs.readFile(specsFile,'utf8')),masterHash=sha(await fs.readFile(template.master)),renderer=config.runtime?.renderer??'python-pptx';
  const rendererFiles=['engine/bin/build-python.mjs','engine/renderer/providers/python_pptx_renderer.py','engine/preview/quicklook-provider.mjs','engine/qa/rendered-visual-qa.mjs'];
  await stage(p,'RENDERING',sha([renderer,slideHash,masterHash,visualSignature,await codeFingerprint(rendererFiles)]),[final],async()=>{let details='';try{details=await invokeRenderer(root,template,folder,renderer)}catch(e){details=e.details??e.message;throw e}finally{await fs.writeFile(path.join(p.dir,'logs/render.log'),details).catch(()=>{});}});p.manifest.renderer=renderer;await save(p);
  p.manifest.status='QA';await save(p);const report=JSON.parse(await fs.readFile(path.join(folder,'render/qa-report.json'),'utf8'));if(!report.summary?.passed)throw new Error('QA 未通过；请查看 qa-report.json。');const packageDir=path.join(p.dir,'output'),name=p.id+'.pptx';await fs.copyFile(final,path.join(packageDir,name));const preview=path.join(folder,'render/preview/AI-Picture.pdf');if(config.output.preview)await fs.copyFile(preview,path.join(packageDir,p.id+'-preview.pdf')).catch(()=>{});const src=researchEligible?path.join(folder,'sources-appendix.md'):path.join(folder,'sources.md');if(config.output.sources)await fs.copyFile(src,path.join(packageDir,p.id+'-sources.md'));
  p.manifest.outputs={pptx:path.join(packageDir,name),preview:config.output.preview?path.join(packageDir,p.id+'-preview.pdf'):null,sources:config.output.sources?path.join(packageDir,p.id+'-sources.md'):null,artifacts:folder};p.manifest.qa=report.summary;const currentSlides=JSON.parse(await fs.readFile(specsFile,'utf8'));p.manifest.slide_count=currentSlides.length;const quality=evaluate({subject:p.id,slides:currentSlides,deck:JSON.parse(await fs.readFile(path.join(folder,'deck-plan.json'),'utf8')),sources:dataset?.sources??[],insights:researchEligible?JSON.parse(await fs.readFile(path.join(folder,'insights.json'),'utf8')):[],qa:report});await write(path.join(p.dir,'qa/quality-report.json'),quality);p.manifest.quality_review={issues:quality.issues.length,assessed:quality.assessed,not_assessed:quality.not_assessed};p.manifest.visual=visualManifest?{...visualManifest.coverage.summary,used_assets:visualManifest.assets.filter(a=>a.used).length,missing:visualManifest.coverage.slots.filter(x=>x.status==='NOT_FOUND').map(x=>x.slot_id)}:null;p.manifest.local_usage={presentation_type:config.presentation.type,slide_count:p.manifest.slide_count,research_time_ms:p.manifest.stages.RESEARCHING?.duration_ms??0,render_time_ms:p.manifest.stages.RENDERING?.duration_ms??0,repair_count:0,qa_issue_count:report.summary.total};p.manifest.status=researchEligible?'COMPLETED_RESEARCH_READOUT':'COMPLETED_LOCAL_EVIDENCE_DECK';p.manifest.limitations=researchEligible?[config.research.source_mode==='hybrid'?'结合本地材料与当前网页证据；未经内部确认的策略仍不视为定案':'仅当前已核验网页样本；没有内部证据时不推导 TCL 策略']:['仅基于用户提供的本地材料；数据缺口已在文稿中明确标出'];await save(p);if(await checkpoint('final_preview'))return p;return p;}
export async function approveCheckpoint(root,id,name){const file=path.join(root,'projects',id,'manifest.json');const m=JSON.parse(await fs.readFile(file,'utf8'));if(m.checkpoint!==name)throw new Error(`当前项目未等待 ${name} 确认`);m.approvals={...m.approvals,[name]:new Date().toISOString()};m.checkpoint=null;m.status='APPROVED';await write(file,m);return m;}
