// Product Reasoning adapter: intentionally separate from Research, and explicitly scoped.
// A sparse dataset produces a research readout, not a speculative TCL strategy.
import fs from 'node:fs/promises';import path from 'node:path';
import {citationsForSlide} from '../research/citation/index.mjs';import {matchSlideAssets} from '../research/visual/slide-matcher/index.mjs';
const ev=(dataset,brands,caps)=>dataset.evidence.filter(e=>brands.includes(e.entity)&&caps.includes(e.capability));
export async function makeEvidenceDeck(dataset,root,out,{domainContext=null,visualManifest=null}={}) {
  const templates=JSON.parse(await fs.readFile(path.join(root,'tests/fixtures/render-test/slide-specs.json'),'utf8'));
  const deck=JSON.parse(await fs.readFile(path.join(root,'tests/fixtures/render-test/deck-plan.json'),'utf8'));
  const brands=dataset.research_plan.brief.brands;const E=(b,c)=>ev(dataset,b,c);const all=dataset.evidence;
  // Cross-brand interpretation is not a research fact or an unsupported industry-wide trend.
  const shared=brands.every(b=>E([b],['Auto Picture Adjustment']).length>0);
  const insight={insight_id:'ins-ai-picture-public-claims',level:'INSIGHT',statement:shared?'在此次三家官方页面样本中，均可找到自动画质优化的公开描述。':'当前样本不足以概括三家自动画质优化的共同趋势。',upstream_ids:brands.map(b=>E([b],['Auto Picture Adjustment'])[0]?.claim_id).filter(Boolean),source_ids:[...new Set(E(brands,['Auto Picture Adjustment']).map(e=>e.source_id))],supporting_evidence:E(brands,['Auto Picture Adjustment']).map(e=>e.evidence_id),reasoning_summary:'限定于本次官方页面样本，不推断市场普及度、效果优劣或 TCL 机会。',confidence:shared?'medium':'low',status:shared?'supported':'needs_evidence'};
  const set=(i,title,conclusion,analysis,data,viz,used)=>{const s=templates[i-1];s.title=title;s.key_message=conclusion;s.content={conclusion,analysis,implication:'研究范围仅限此次已核验公开页面。',structured_data:data??{},speaker_note:null};if(viz)s.visualization.data=viz;s.evidence=used.map(e=>({evidence_id:e.evidence_id,claim:dataset.claims.find(c=>c.claim_id===e.claim_id)?.statement??e.quote_or_fact,evidence_type:'fact',status:'supported',source_ids:[e.source_id],note:`原文：${e.quote_or_fact}`}));s.sources=[...new Set(used.map(e=>e.source_id))];s.render_options.source_labels=s.sources.map(id=>{const src=allSources.find(x=>x.source_id===id);return `${src?.publisher??id} (${src?.locator.accessed_at?.slice(0,10)??'unknown'})`;});s.render_options.source_urls=s.sources.map(id=>allSources.find(x=>x.source_id===id)?.locator.uri??'');s.notes=[`research evidence: ${used.map(e=>e.evidence_id).join(', ')}`];s.status='ready_for_renderer';return s;};
  const allSources=dataset.sources;
  set(1,'AI Picture 官方能力证据概览','三家公开页面证据与研究缺口并列呈现',[],{subtitle:'Product PPT Agent · Official evidence · '+new Date().toISOString().slice(0,10)},null,[]);
  set(2,'三家官网均描述自动画质优化',insight.statement,['仅说明本次样本，未证明行业普遍趋势','个性化与环境适配的证据覆盖不均衡'],{headline:insight.statement,findings:brands.map(b=>({title:b,body:({Samsung:'按内容类型与偏好自动调整色彩和对比度',Sony:'XR Processor 描述场景识别和画面优化',Hisense:'Hi-View 引擎描述按观看内容优化画质'})[b]??'未找到可靠证据'})),decision:'下一步需核验具体型号、地区、用户体验与 TCL 内部能力。'},null,E(brands,['Auto Picture Adjustment']));
  set(3,`研究覆盖：${dataset.coverage.overall.found} / ${dataset.coverage.overall.required} 项找到官网原文`,'覆盖率反映当前研究完成度，不是产品能力评分',['每家按相同十项研究需求计数'],{big_number:{value:`${dataset.coverage.overall.found}/${dataset.coverage.overall.required}`,label:'本次证据覆盖'}},{categories:brands,series:[{name:'有官网证据',values:dataset.coverage.rows.map(r=>r.found)},{name:'仍待研究',values:dataset.coverage.rows.map(r=>r.required-r.found)}]},all);
  set(4,'证据路径：从页面原文到有限解释','只对官网可直接支持的能力打勾',['问号表示本次未找到，不等于厂商没有此能力'],{}, {stages:[{name:'发现',action:'官方页面',pain:'型号/地区差异',opportunity:'记录 URL'},{name:'提取',action:'原文命中',pain:'营销表述',opportunity:'保留上下文'},{name:'核验',action:'Claim → Evidence',pain:'证据范围有限',opportunity:'标记缺口'},{name:'分析',action:'有界洞察',pain:'不能越界推断',opportunity:'补内部数据'}]},all);
  set(5,'自动优化有共同描述，细项证据不同','官网描述不同；未找到的字段保持问号',['每项结果可回溯至 Evidence ID'],{competitors:brands.map(b=>({name:b,summary:['AI Processing','Scene Detection','User Preference / Personalization'].map(c=>`${c}: ${dataset.competitor_matrix.rows.find(r=>r.capability===c)?.cells[b].value}`).join('\n')}))},null,all);
  templates[5].layout.layout_id='L09_COMPETITOR_4COL';templates[5].layout.preferred='L09_COMPETITOR_4COL';templates[5].visualization={type:'text',reason:'缺口计数对比，不代表功能不存在',data:null};
  const gapMessage=domainContext?.packs?.some(x=>x.id==='tv-picture-quality')?`${dataset.coverage.overall.required-dataset.coverage.overall.found} 项待研究；优先核验场景识别、环境适配与用户控制（研究建议）`:`共 ${dataset.coverage.overall.required-dataset.coverage.overall.found} 项仍待研究，不可直接推断能力缺失`;
  set(6,'缺口不等于竞品不支持',gapMessage,['每家按 10 项统一字段检查'],{competitors:brands.map((b,i)=>({name:b,summary:`${dataset.coverage.rows[i].found} / ${dataset.coverage.rows[i].required} 项已核验\n${dataset.coverage.rows[i].gaps.length} 项待研究\n“?” 不是“不支持”`}))},null,all);
  set(7,'研究到策略须经过证据关口','本轮仅形成有限洞察，尚未形成 TCL 策略',['需要用户问题、内部能力和效果验证'],{}, {goal:'当前只支持官网公开能力对比',pillars:[{title:'事实',body:'原文命中\nSource URL'},{title:'解释',body:'三家样本共性\n不外推行业'},{title:'缺口',body:'型号 / 地区\n用户体验'}],foundation:'策略与功能提案：待后续 Product Reasoning 和内部资料'},all);
  set(8,'结论可追溯至页面原文','Insight → Claim → Evidence → Source',['证据对象与推理对象分离'],{}, {layers:[{name:'Insight',items:[insight.insight_id]},{name:'Claim',items:insight.upstream_ids},{name:'Evidence',items:insight.supporting_evidence},{name:'Source',items:insight.source_ids}]},E(brands,['Auto Picture Adjustment']));
  set(9,'后续研究：补齐关键空白','优先核验同型号 / 同市场，再引入用户与内部数据',['此页是研究计划，不是产品 Roadmap'],{}, {phases:[{phase:'补官网资料',goal:'提高同口径覆盖',deliverables:['功能文档','型号/地区'],exit:'证据回链完整'},{phase:'体验研究',goal:'验证实际交互',deliverables:['用户任务','效果观察'],exit:'体验问题有证据'},{phase:'产品推理',goal:'提出有界机会',deliverables:['TCL 内部数据','可测假设'],exit:'策略逻辑可追溯'}]},all);
  set(10,'THANKS','研究证据到此为止',[],{},null,[]);
  if(domainContext?.packs?.length){templates[4].notes.push(`方法上下文：${domainContext.packs.map(x=>x.id).join(', ')}；维度：${domainContext.dimensions.join(', ')}。仅作为提问范围，不充当产品事实。`);}
  let visualMatch={used:[],missing:[]};if(visualManifest){
    templates[4].visual_requirement={priority:'high',types:['product_image'],entities:brands,usage:'competitor_product_context'};
    templates[5].visual_requirement={priority:'high',types:['feature_image'],entities:brands,usage:'picture_capability_explanation'};
    visualMatch=matchSlideAssets(templates,visualManifest);templates.splice(0,templates.length,...visualMatch.slides);
    const appendix=visualMatch.used.map(u=>{const a=visualManifest.assets.find(x=>x.asset_id===u.asset_id);return `- Slide ${u.slide_id}: ${u.entity} ${a.asset_type} [${a.asset_id}] — ${a.source.page_url} | asset: ${a.source.asset_url??a.source_url} | internal review only, external reuse rights unverified.`;});
    await fs.writeFile(path.join(out,'visual-citations.md'),'# Visual Sources\n'+appendix.join('\n')+'\n');
  }
  // Deck Plan remains the existing renderer contract, but all mock claims are replaced.
  deck.deck_id='deck-ai-picture-evidence-2026';deck.deck_title='AI Picture 官方能力证据概览';deck.core_message=insight.statement;deck.objective='对三家官方页面已核验能力做有界比较';deck.open_questions=dataset.coverage.rows.flatMap(r=>r.gaps);
  deck.slides.forEach((p,i)=>{p.key_message=templates[i].key_message;p.purpose=templates[i].title;p.evidence_needed=templates[i].evidence.map(e=>e.evidence_id);if(templates[i].visual_requirement)p.visual_requirement=templates[i].visual_requirement;});
  await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'insights.json'),JSON.stringify([insight],null,2));await fs.writeFile(path.join(out,'deck-plan.json'),JSON.stringify(deck,null,2));await fs.writeFile(path.join(out,'slide-specs.json'),JSON.stringify(templates,null,2));
  const citations=templates.map((s,i)=>({slide:i+1,...citationsForSlide(s,all,allSources)}));await fs.writeFile(path.join(out,'citations.json'),JSON.stringify(citations,null,2));
  await fs.writeFile(path.join(out,'sources-appendix.md'),'# Sources Appendix\n'+allSources.map((s,i)=>`[${i+1}] ${s.title}. ${s.locator.uri} (accessed ${s.locator.accessed_at})`).join('\n')+'\n'+(visualManifest?'\n## Visual Sources (internal review only)\n'+visualMatch.used.map(u=>{const a=visualManifest.assets.find(x=>x.asset_id===u.asset_id);return `- ${u.slide_id} ${u.entity} [${a.asset_id}] ${a.source.page_url} ; asset URL: ${a.source.asset_url??a.source_url} ; reuse rights unverified`;}).join('\n')+'\n':''));
  return {deck,slides:templates,insight,visualMatch};
}
