// Product Reasoning adapter: intentionally separate from Research, and explicitly scoped.
// A sparse dataset produces a research readout, not a speculative TCL strategy.
import fs from 'node:fs/promises';import path from 'node:path';
import {citationsForSlide} from '../research/citation/index.mjs';import {matchSlideAssets} from '../research/visual/slide-matcher/index.mjs';
const ev=(dataset,brands,caps)=>dataset.evidence.filter(e=>brands.includes(e.entity)&&caps.includes(e.capability));
export async function makeEvidenceDeck(dataset,root,out,{domainContext=null,visualManifest=null,localInputs=[]}={}) {
  const templates=JSON.parse(await fs.readFile(path.join(root,'tests/fixtures/render-test/slide-specs.json'),'utf8'));
  const deck=JSON.parse(await fs.readFile(path.join(root,'tests/fixtures/render-test/deck-plan.json'),'utf8'));
  const brands=dataset.research_plan.brief.brands;const E=(b,c)=>ev(dataset,b,c);const all=dataset.evidence,topic=dataset.research_plan.brief.topic??dataset.research_plan.brief.objective??'产品研究',capabilities=dataset.competitor_matrix.rows.map(x=>x.capability),sharedCapability=capabilities.find(cap=>brands.every(b=>E([b],[cap]).length>0)),sharedEvidence=sharedCapability?E(brands,[sharedCapability]):all.slice(0,Math.max(1,brands.length));
  // Cross-brand interpretation is bounded to the verified source sample.
  const shared=!!sharedCapability;
  const insight={insight_id:'ins-public-evidence',level:'INSIGHT',statement:shared?`在本次已核验页面中，${brands.length} 个研究对象都提及“${sharedCapability}”。`:`当前已核验页面仍不足以得出 ${topic} 的跨对象共同结论。`,upstream_ids:sharedEvidence.map(e=>e.claim_id),source_ids:[...new Set(sharedEvidence.map(e=>e.source_id))],supporting_evidence:sharedEvidence.map(e=>e.evidence_id),reasoning_summary:'限定于本次已核验公开页面，不推断市场普及度、效果优劣或本方产品策略。',confidence:shared?'medium':'low',status:shared?'supported':'needs_evidence'};
  const set=(i,title,conclusion,analysis,data,viz,used)=>{const s=templates[i-1];s.title=title;s.key_message=conclusion;s.content={conclusion,analysis,implication:'研究范围仅限此次已核验公开页面。',structured_data:data??{},speaker_note:null};if(viz)s.visualization.data=viz;s.evidence=used.map(e=>({evidence_id:e.evidence_id,claim:dataset.claims.find(c=>c.claim_id===e.claim_id)?.statement??e.quote_or_fact,evidence_type:'fact',status:'supported',source_ids:[e.source_id],note:`原文：${e.quote_or_fact}`}));s.sources=[...new Set(used.map(e=>e.source_id))];s.render_options.source_labels=s.sources.map(id=>{const src=allSources.find(x=>x.source_id===id);return `${src?.publisher??id} (${src?.locator.accessed_at?.slice(0,10)??'unknown'})`;});s.render_options.source_urls=s.sources.map(id=>allSources.find(x=>x.source_id===id)?.locator.uri??'');s.notes=[`research evidence: ${used.map(e=>e.evidence_id).join(', ')}`];s.status='ready_for_renderer';return s;};
  const allSources=dataset.sources;
  set(1,`${topic} 公开证据概览`,'将已核验网页证据、覆盖范围和研究缺口并列呈现',[],{subtitle:'Product PPT Agent · Web research · '+new Date().toISOString().slice(0,10)},null,[]);
  set(2,shared?`已核验页面中出现共同主题：${sharedCapability}`:'当前证据尚未形成跨对象共同结论',insight.statement,['结论只适用于本次已核验页面','未找到的字段保持为未知'],{headline:insight.statement,findings:brands.slice(0,3).map(b=>{const claims=dataset.claims.filter(c=>c.entity===b&&c.status==='SUPPORTED');return {title:b,body:claims[0]?.statement??'未找到可直接支持的声明'};}),decision:'策略和功能决策仍需用户证据、内部能力和效果验证。'},null,sharedEvidence);
  set(3,`研究覆盖：${dataset.coverage.overall.found} / ${dataset.coverage.overall.required} 项找到官网原文`,'覆盖率反映当前研究完成度，不是产品能力评分',['每家按相同十项研究需求计数'],{big_number:{value:`${dataset.coverage.overall.found}/${dataset.coverage.overall.required}`,label:'本次证据覆盖'}},{categories:brands,series:[{name:'有官网证据',values:dataset.coverage.rows.map(r=>r.found)},{name:'仍待研究',values:dataset.coverage.rows.map(r=>r.required-r.found)}]},all);
  set(4,'证据路径：从页面原文到有限解释','只对官网可直接支持的能力打勾',['问号表示本次未找到，不等于厂商没有此能力'],{}, {stages:[{name:'发现',action:'官方页面',pain:'型号/地区差异',opportunity:'记录 URL'},{name:'提取',action:'原文命中',pain:'营销表述',opportunity:'保留上下文'},{name:'核验',action:'Claim → Evidence',pain:'证据范围有限',opportunity:'标记缺口'},{name:'分析',action:'有界洞察',pain:'不能越界推断',opportunity:'补内部数据'}]},all);
  const comparisonCaps=capabilities.slice(0,3);set(5,'公开证据的共性与差异','未找到的字段保持问号，不解读为不支持',['每项结果可回溯至 Evidence ID'],{competitors:brands.map(b=>({name:b,summary:comparisonCaps.map(c=>`${c}: ${dataset.competitor_matrix.rows.find(r=>r.capability===c)?.cells[b].value??'?'}`).join('\n')}))},null,all);
  templates[5].layout.layout_id='L09_COMPETITOR_4COL';templates[5].layout.preferred='L09_COMPETITOR_4COL';templates[5].visualization={type:'text',reason:'缺口计数对比，不代表功能不存在',data:null};
  const gapMessage=`共 ${dataset.coverage.overall.required-dataset.coverage.overall.found} 项仍待研究，不可直接推断能力缺失`;
  set(6,'缺口不等于竞品不支持',gapMessage,['每家按 10 项统一字段检查'],{competitors:brands.map((b,i)=>({name:b,summary:`${dataset.coverage.rows[i].found} / ${dataset.coverage.rows[i].required} 项已核验\n${dataset.coverage.rows[i].gaps.length} 项待研究\n“?” 不是“不支持”`}))},null,all);
  set(7,'研究到策略须经过证据关口','本轮仅形成有限洞察，尚未形成 TCL 策略',['需要用户问题、内部能力和效果验证'],{}, {goal:'当前只支持官网公开能力对比',pillars:[{title:'事实',body:'原文命中\nSource URL'},{title:'解释',body:'三家样本共性\n不外推行业'},{title:'缺口',body:'型号 / 地区\n用户体验'}],foundation:'策略与功能提案：待后续 Product Reasoning 和内部资料'},all);
  set(8,'结论可追溯至页面原文','Insight → Claim → Evidence → Source',['证据对象与推理对象分离'],{}, {layers:[{name:'Insight',items:[insight.insight_id]},{name:'Claim',items:insight.upstream_ids},{name:'Evidence',items:insight.supporting_evidence},{name:'Source',items:insight.source_ids}]},sharedEvidence);
  set(9,'后续研究：补齐关键空白','优先核验同型号 / 同市场，再引入用户与内部数据',['此页是研究计划，不是产品 Roadmap'],{}, {phases:[{phase:'补官网资料',goal:'提高同口径覆盖',deliverables:['功能文档','型号/地区'],exit:'证据回链完整'},{phase:'体验研究',goal:'验证实际交互',deliverables:['用户任务','效果观察'],exit:'体验问题有证据'},{phase:'产品推理',goal:'提出有界机会',deliverables:['TCL 内部数据','可测假设'],exit:'策略逻辑可追溯'}]},all);
  set(10,'THANKS','研究证据到此为止',[],{},null,[]);
  if(localInputs.length){const localSources=localInputs.map((input,i)=>({source_id:`src-local-${i+1}`,title:input.name,source_type:'user_provided',locator:{uri:input.name,accessed_at:new Date().toISOString()},status:'provided',publisher:'用户提供',origin:'user_provided'}));allSources.push(...localSources);const excerpts=localInputs.flatMap((input,i)=>String(input.text).replace(/\[第\s*\d+\s*页\]/g,' ').split(/(?<=[。！？.!?])\s+/).map(text=>({text:text.replace(/\s+/g,' ').trim(),source:localSources[i]}))).filter(x=>x.text.length>12).slice(0,3);const local=structuredClone(templates[1]);local.title='本地材料与联网证据同时使用';local.key_message=`${localInputs.length} 个本地文件作为内部上下文，网页证据用于外部核验`;local.content={conclusion:local.key_message,analysis:excerpts.map(x=>x.text),implication:'两类证据分别标注来源，不用公开页面替代内部现状判断。',structured_data:{headline:local.key_message,findings:excerpts.map((x,i)=>({title:`本地证据 ${i+1}`,body:x.text.slice(0,150)})),decision:'仅当本地材料和外部证据在同一口径下一致时，才进一步形成产品判断。'},speaker_note:'混合模式：用户材料未上传到外部网络'};local.layout={...local.layout,layout_id:'L20_EXECUTIVE_SUMMARY',preferred:'L20_EXECUTIVE_SUMMARY'};local.sources=[...new Set(excerpts.map(x=>x.source.source_id))];local.render_options.source_labels=excerpts.map(x=>x.source.title);local.render_options.source_urls=excerpts.map(x=>x.source.locator.uri);local.evidence=excerpts.map((x,i)=>({evidence_id:`ev-local-${i+1}`,claim:x.text.slice(0,180),evidence_type:'quote',status:'supported',source_ids:[x.source.source_id],note:'用户提供的本地材料'}));local.notes=['本地材料仅在本机使用'];local.status='ready_for_renderer';templates.splice(2,0,local);}
  templates.forEach((s,i)=>{s.slide_id=`s${String(i+1).padStart(2,'0')}`;});
  const comparisonSlide=templates.find(s=>s.title==='公开证据的共性与差异'),gapSlide=templates.find(s=>s.title==='缺口不等于竞品不支持');
  if(domainContext?.packs?.length){comparisonSlide.notes.push(`方法上下文：${domainContext.packs.map(x=>x.id).join(', ')}；维度：${domainContext.dimensions.join(', ')}。仅作为提问范围，不充当产品事实。`);}
  let visualMatch={used:[],missing:[]};if(visualManifest){
    comparisonSlide.visual_requirement={priority:'high',types:['product_image','feature_image','feature_screenshot'],entities:brands,usage:'competitor_product_context'};
    visualMatch=matchSlideAssets(templates,visualManifest);templates.splice(0,templates.length,...visualMatch.slides);
    const appendix=visualMatch.used.map(u=>{const a=visualManifest.assets.find(x=>x.asset_id===u.asset_id);return `- Slide ${u.slide_id}: ${u.entity} ${a.asset_type} [${a.asset_id}] — ${a.source.page_url} | asset: ${a.source.asset_url??a.source_url} | internal review only, external reuse rights unverified.`;});
    await fs.writeFile(path.join(out,'visual-citations.md'),'# Visual Sources\n'+appendix.join('\n')+'\n');
  }
  // Deck Plan remains the existing renderer contract, but all mock claims are replaced.
  deck.deck_id='deck-web-evidence-2026';deck.deck_title=`${topic} 公开证据概览`;deck.core_message=insight.statement;deck.objective='对已核验公开页面做有界比较';deck.open_questions=dataset.coverage.rows.flatMap(r=>r.gaps);
  deck.slides=templates.map((s,i)=>({slide_id:s.slide_id,sequence:i+1,section_id:i<4?'sec-evidence':i<templates.length-2?'sec-analysis':'sec-next',purpose:s.purpose??s.title,question:s.title,key_message:s.key_message,evidence_needed:(s.evidence??[]).map(e=>e.evidence_id),analysis_method:s.visualization?.type??'evidence synthesis',visualization_candidate:s.layout?.layout_id??'content',dependencies:i?[templates[i-1].slide_id]:[],...(s.visual_requirement?{visual_requirement:s.visual_requirement}:{})}));
  await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'insights.json'),JSON.stringify([insight],null,2));await fs.writeFile(path.join(out,'deck-plan.json'),JSON.stringify(deck,null,2));await fs.writeFile(path.join(out,'slide-specs.json'),JSON.stringify(templates,null,2));
  const citations=templates.map((s,i)=>({slide:i+1,...citationsForSlide(s,all,allSources)}));await fs.writeFile(path.join(out,'citations.json'),JSON.stringify(citations,null,2));
  await fs.writeFile(path.join(out,'sources-appendix.md'),'# Sources Appendix\n'+allSources.map((s,i)=>`[${i+1}] ${s.title}. ${s.locator.uri} (accessed ${s.locator.accessed_at})`).join('\n')+'\n'+(visualManifest?'\n## Visual Sources (internal review only)\n'+visualMatch.used.map(u=>{const a=visualManifest.assets.find(x=>x.asset_id===u.asset_id);return `- ${u.slide_id} ${u.entity} [${a.asset_id}] ${a.source.page_url} ; asset URL: ${a.source.asset_url??a.source_url} ; reuse rights unverified`;}).join('\n')+'\n':''));
  return {deck,slides:templates,insight,visualMatch};
}
