import fs from 'node:fs/promises';import path from 'node:path';
import {HttpBrowserProvider} from '../browser/index.mjs';import {authority} from '../source/index.mjs';
import {planVisualResearch} from './visual-planner/index.mjs';import {extractPageAssets} from './webpage-asset-extractor/index.mjs';import {rankCandidates} from './asset-ranker/index.mjs';import {downloadCandidate} from './asset-downloader/index.mjs';import {captureFeature} from './screenshot-capture/index.mjs';import {deduplicate} from './deduplication/index.mjs';
const write=(p,x)=>fs.writeFile(p,JSON.stringify(x,null,2)+'\n');
export function visualCoverage(plan,assets){return {generated_at:new Date().toISOString(),slots:plan.slots.map(slot=>{const found=assets.filter(a=>a.entity===slot.entity&&a.asset_type===slot.asset_type&&a.status!=='DUPLICATE_ASSET');return {slot_id:slot.id,slide_id:slot.slide_id,entity:slot.entity,asset_type:slot.asset_type,found:found.length>0,usable:found.some(a=>a.status==='approved_internal'),used:found.some(a=>a.used),asset_ids:found.map(a=>a.asset_id),status:found.some(a=>a.used)?'USED':found.some(a=>a.status==='approved_internal')?'USABLE':found.length?'REVIEW_REQUIRED':'NOT_FOUND'};}),summary:{required:plan.slots.length,found:plan.slots.filter(s=>assets.some(a=>a.entity===s.entity&&a.asset_type===s.asset_type&&a.status!=='DUPLICATE_ASSET')).length,usable:plan.slots.filter(s=>assets.some(a=>a.entity===s.entity&&a.asset_type===s.asset_type&&a.status==='approved_internal')).length,used:plan.slots.filter(s=>assets.some(a=>a.entity===s.entity&&a.asset_type===s.asset_type&&a.used)).length}};}
export async function runVisualResearch({dataset,brief,outputDir,browser=new HttpBrowserProvider(),reviewDecisions=[]}){
 const dir=path.join(outputDir,'assets'),plan=planVisualResearch(dataset),assets=[],attempts=[],pages=new Map(),existing=[];await fs.mkdir(dir,{recursive:true});
 const idFor=(brand,kind)=>`src-visual-${brand.toLowerCase()}-${kind}`;
 for(const request of brief.requests??[]){const brand=request.brand;for(const kind of ['product','feature']){const url=request[kind+'_page'];if(!url)continue;const source_id=dataset.sources.find(s=>s.locator.uri===url)?.source_id??idFor(brand,kind);let page=pages.get(url);try{if(!page){page=await browser.open(url);pages.set(url,page);}if(authority(page.url)!=='A')throw new Error('Not an official page');const candidates=extractPageAssets(page);const hint=request[kind+'_hint']??'';const matches=hint?candidates.filter(c=>c.url.toLowerCase().includes(hint.toLowerCase())||c.alt.toLowerCase().includes(hint.toLowerCase())):rankCandidates(candidates,{brand,type:kind==='product'?'product_image':'feature_image',terms:['AI','Picture']}).slice(0,3);if(!matches.length)throw new Error('No matching official-page image candidates');let success=false;for(const candidate of matches.slice(0,3)){try{const ranked=rankCandidates([candidate],{brand,type:kind==='product'?'product_image':'feature_image',terms:['AI','Picture']})[0];const asset=await downloadCandidate(ranked,page,{dir:path.join(dir,'official',kind),source_id,entity:brand,asset_type:kind==='product'?'product_image':'feature_image',related_evidence:dataset.evidence.filter(e=>e.entity===brand).map(e=>e.evidence_id)});assets.push(asset);attempts.push({brand,kind,url:candidate.url,status:asset.status,asset_id:asset.asset_id});success=true;break;}catch(e){attempts.push({brand,kind,url:candidate.url,status:'FAILED',error:e.message});}}if(!success)throw new Error('All image candidates failed');}catch(e){attempts.push({brand,kind,page_url:url,status:'NOT_FOUND',error:e.message});}}
 const shotUrl=request.screenshot_page??request.feature_page;if(shotUrl&&request.screenshot_text){try{const a=await captureFeature({url:shotUrl,source_id:dataset.sources.find(s=>s.locator.uri===shotUrl)?.source_id??idFor(brand,'screenshot'),brand,text:request.screenshot_text,dir:path.join(dir,'screenshots')});assets.push(a);attempts.push({brand,kind:'screenshot',url:shotUrl,status:a.status,asset_id:a.asset_id});}catch(e){attempts.push({brand,kind:'screenshot',url:shotUrl,status:'NOT_FOUND',error:e.message.slice(0,180)});}}}
 const {kept,rejected}=deduplicate(assets);const all=[...kept,...rejected];for(const a of all){const decision=reviewDecisions.find(x=>x.content_hash===a.content_hash&&x.entity===a.entity&&x.asset_type===a.asset_type);if(!decision||a.status!=='review_required')continue;a.status='approved_internal';a.semantic_review='human_verified_for_internal_use';a.semantic_description=decision.description;a.visual_content=decision.visual_content??[];a.quality.watermark=decision.watermark??'not_assessed';a.quality.text_density=decision.text_density??'not_assessed';a.quality.visual_clarity=decision.visual_clarity??'not_assessed';a.rights={status:'internal_review_only',scope:'internal_review',reviewer:decision.reviewer,reviewed_at:decision.reviewed_at};}
 const coverage=visualCoverage(plan,all);const qa={issues:all.flatMap(a=>{const out=[];if(a.status==='LOW_RESOLUTION')out.push({code:'IMAGE_LOW_RESOLUTION',asset_id:a.asset_id});if(a.status==='DUPLICATE_ASSET')out.push({code:'IMAGE_DUPLICATED',asset_id:a.asset_id});if(a.status==='review_required')out.push({code:'IMAGE_REVIEW_PENDING',asset_id:a.asset_id});if(!a.source_page_url)out.push({code:'IMAGE_SOURCE_MISSING',asset_id:a.asset_id});return out;}),not_assessed:['OCR/text density and watermark for unreviewed candidates','Legal reuse rights for all external assets'],status:'partial'};
 await write(path.join(dir,'visual-plan.json'),plan);await write(path.join(dir,'asset-manifest.json'),{generated_at:new Date().toISOString(),assets:all,attempts,coverage,qa});await write(path.join(dir,'visual-coverage.json'),coverage);await write(path.join(dir,'visual-qa.json'),qa);return {plan,assets:all,attempts,coverage,qa,manifest_path:path.join(dir,'asset-manifest.json')};
}
