import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {retrieveContext,rankItems,health} from '../../engine/knowledge/index.mjs';import {learnCandidate,promoteCandidate,rejectCandidate,reviewPptx} from '../../app/review/index.mjs';import {diffSlides,recordFeedback,confirmFeedback,preferenceCandidates} from '../../app/feedback/index.mjs';import {createSkill} from '../../app/feedback/skill-builder.mjs';import {evaluate} from '../../engine/critic/index.mjs';import {recordDecision} from '../../app/knowledge/decision.mjs';import {isStale} from '../../engine/knowledge/index.mjs';import {createPptxFixture} from '../helpers/pptx-fixture.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
test('A: topic-specific packs select relevant axes without becoming product facts',async()=>{const config={project:{name:'AI Picture 竞品分析'},presentation:{brief:'AI Picture Samsung Sony Hisense',type:'competitor-analysis'}};const generic=await retrieveContext(root,config,{enabled:false}),department=await retrieveContext(root,config);assert.equal(generic.packs.length,0);assert.deepEqual(department.packs.map(x=>x.id),['tv-picture-quality','ai-tv','product-management']);assert.ok(department.dimensions.includes('Scene Detection'));assert.equal(department.approved_knowledge.length,0);assert.ok(department.references.every(x=>x.usage==='question_framework_not_fact'));});
test('B: learn extracts candidate only; explicit human gate required to promote',async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-phase5-'));try{await fs.mkdir(path.join(tmp,'tools'),{recursive:true});await fs.copyFile(path.join(root,'tools/extract_pptx_text.py'),path.join(tmp,'tools/extract_pptx_text.py'));const deck=await createPptxFixture(path.join(tmp,'fixtures/phase5.pptx'),'phase5');const {candidate}=await learnCandidate(tmp,deck);assert.equal(candidate.status,'candidate');assert.ok(candidate.structure.slide_count>=3);assert.equal(JSON.stringify(candidate).includes('自动优化有共同描述'),false);await assert.rejects(promoteCandidate(tmp,candidate.id,{}),/必须显式/);const output=await promoteCandidate(tmp,candidate.id,{confirm:true,reviewer:'test-reviewer',reason:'isolated unit test only',scope:'test-only slide structure'});const approved=JSON.parse(await fs.readFile(output,'utf8'));assert.equal(approved.status,'approved');assert.equal(approved.confidence,'low');assert.ok(approved.structure.roles.length>=3);}finally{await fs.rm(tmp,{recursive:true,force:true});}});
test('C: 5 titles + 2 layouts + 1 deletion remain unclassified signals',async()=>{const before=JSON.parse(await fs.readFile(path.join(root,'tests/ai-picture/slide-specs.json'),'utf8'));const after=structuredClone(before);for(let i=1;i<=5;i++)after[i].title+='（编辑）';after[2].layout.layout_id='L01_TITLE_TEXT';after[3].layout.layout_id='L01_TITLE_TEXT';after.splice(8,1);const signals=diffSlides('test-project',before,after);assert.equal(signals.length,8);assert.deepEqual(signals.reduce((a,x)=>(a[x.feedback_type]=(a[x.feedback_type]??0)+1,a),{}),{title_edit:5,layout_change:2,slide_deleted:1});assert.ok(signals.every(x=>x.signal_class==='UNCLASSIFIED'&&x.status==='pending_review'));});
test('confirmed preference needs repeat across three distinct projects',async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-feedback-'));try{for(const id of ['a','b','c']){const entry={feedback_id:'fb-'+id,project_id:id,slide_id:'s02',feedback_type:'title_edit',category:'content',signal_class:'UNCLASSIFIED',original:'long',updated:'short',comment:'',timestamp:new Date().toISOString(),status:'pending_review'};await recordFeedback(tmp,id,[entry]);}assert.deepEqual(await preferenceCandidates(tmp),[]);for(const id of ['a','b','c'])await confirmFeedback(tmp,id,'fb-'+id,{signal_class:'PREFERENCE',reason:'Explicit test review'});const p=await preferenceCandidates(tmp);assert.equal(p.length,1);assert.equal(p[0].status,'candidate_only');}finally{await fs.rm(tmp,{recursive:true,force:true});}});
test('critic reports unknown instead of fabricated visual grade',()=>{const report=evaluate({subject:'imported',slides:[{slide_type:'content',title:'全面提升用户体验',content:{structured_data:{body:'Test'}}}],imported:true});assert.equal(report.score,null);assert.ok(report.not_assessed.includes('Visual_Hierarchy'));assert.ok(report.issues.some(x=>x.code==='VAGUE_TITLE'));});
test('retrieval excludes candidates and expired approved items',()=>{const items=[{id:'a',status:'candidate',statement:'AI Picture',tags:[],domain:'tv',last_updated:new Date().toISOString(),confidence:'high'},{id:'b',status:'approved',statement:'AI Picture',tags:[],domain:'tv',last_updated:'2020-01-01T00:00:00Z',valid_until:'2021-01-01T00:00:00Z',confidence:'high'}];assert.deepEqual(rankItems(items,'AI Picture'),[]);});
test('skill builder creates disabled draft without changing core',async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-skill-'));try{await fs.mkdir(path.join(tmp,'skills/custom'),{recursive:true});const dir=await createSkill(tmp,'tv-sound-evaluation');const m=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8'));assert.equal(m.enabled,false);await assert.rejects(createSkill(tmp,'tv-sound-evaluation'),/已存在/);}finally{await fs.rm(tmp,{recursive:true,force:true});}});

test('historical decision requires explicit source and remains scoped',async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-decision-'));try{const source=path.join(tmp,'approved-source.md');await fs.writeFile(source,'Synthetic decision evidence for a unit test only');await assert.rejects(recordDecision(tmp,{statement:'Test decision',scope:'test-only',source,decision_date:'2025-01-01'}),/需 --confirm/);const file=await recordDecision(tmp,{statement:'Test decision',scope:'test-only',source,decision_date:'2025-01-01',reviewer:'test-reviewer',reason:'isolated synthetic check',confirm:true});const x=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(x.kind,'historical_decision');assert.match(x.limitations.join(' '),/current/);}finally{await fs.rm(tmp,{recursive:true,force:true});}});
test('knowledge TTL flags volatile facts while stable methods have no forced expiry',()=>{const old='2020-01-01T00:00:00Z';assert.equal(isStale({last_updated:old,tags:['price']}),true);assert.equal(isStale({last_updated:old,tags:['product-spec']}),true);assert.equal(isStale({last_updated:old,tags:['method']}),false);});

test('explicit rejection keeps candidate out of retrieval',async()=>{const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-reject-'));try{const dir=path.join(tmp,'knowledge-base/candidates');await fs.mkdir(dir,{recursive:true});const id='kb-0000000000000001';await fs.writeFile(path.join(dir,id+'.json'),JSON.stringify({id,status:'candidate'}));await assert.rejects(rejectCandidate(tmp,id,{}),/需 --confirm/);await rejectCandidate(tmp,id,{confirm:true,reviewer:'test-reviewer',reason:'test-only insufficient evidence'});const item=JSON.parse(await fs.readFile(path.join(dir,id+'.json'),'utf8'));assert.equal(item.status,'rejected');}finally{await fs.rm(tmp,{recursive:true,force:true});}});
