import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';
import {learnCandidate} from '../review/index.mjs';import {ingestCandidate} from './ingest.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
export async function resolveLearningLibrary(root,requested=null){if(requested){const p=path.resolve(requested);await fs.access(p);return p;}const personal=path.join(root,'workspace/旧PPT库');await fs.mkdir(personal,{recursive:true});return personal;}
export async function learnDirectory(root,sourceDir,{manifestPath=path.join(root,'workspace/learning-manifest.json'),limit=100}={}){
 const dir=path.resolve(sourceDir),entries=(await fs.readdir(dir,{withFileTypes:true})).filter(x=>x.isFile()&&/\.(?:pptx|pdf)$/i.test(x.name)&&!x.name.startsWith('.~')&&!x.name.startsWith('~$')).sort((a,b)=>a.name.localeCompare(b.name));if(entries.length>limit)throw new Error(`旧库文件 ${entries.length} 超过每次上限 ${limit}`);
 await fs.mkdir(path.dirname(manifestPath),{recursive:true});let manifest={version:'1.0.0',source_dir:dir,files:{},history:[]};try{manifest=JSON.parse(await fs.readFile(manifestPath,'utf8'));if(manifest.source_dir!==dir)throw new Error('学习清单绑定了其他旧库；请使用独立 --manifest。')}catch(e){if(e.code!=='ENOENT')throw e;}
 const result={source_dir:dir,manifest_path:manifestPath,discovered:entries.length,learned:[],skipped:[],failed:[],ignored:(await fs.readdir(dir)).filter(x=>x.startsWith('.~')||x.startsWith('~$'))};
 for(const entry of entries){const file=path.join(dir,entry.name),stat=await fs.stat(file),hash=sha(await fs.readFile(file)),prev=manifest.files[file];if(prev?.hash===hash&&prev.status==='candidate_created'){result.skipped.push({file,reason:'unchanged_hash'});prev.modified_at=stat.mtime.toISOString();continue;}
  try{const item=entry.name.toLowerCase().endsWith('.pptx')?await learnCandidate(root,file,{scope:'historical-presentation-unreviewed'}):await ingestCandidate(root,file,{scope:'historical-pdf-unreviewed'});if(prev&&prev.hash!==hash)manifest.history.push({file,hash:prev.hash,candidate_ids:prev.candidate_ids??[],superseded_at:new Date().toISOString()});manifest.files[file]={file,hash,modified_at:stat.mtime.toISOString(),learned_at:new Date().toISOString(),status:'candidate_created',candidate_ids:[item.candidate.id],extracted_patterns:item.candidate.kind==='pattern'?[item.candidate.id]:[],file_type:path.extname(file).slice(1),limitations:item.candidate.limitations};result.learned.push({file,candidate_id:item.candidate.id,kind:item.candidate.kind});}
  catch(e){manifest.files[file]={file,hash,modified_at:stat.mtime.toISOString(),learned_at:new Date().toISOString(),status:/没有可提取文本|扫描件/.test(e.message)?'needs_ocr':'failed',error:e.message.slice(0,250),candidate_ids:[],extracted_patterns:[]};result.failed.push({file,error:e.message.slice(0,250)});} }
 manifest.updated_at=new Date().toISOString();const temp=manifestPath+'.tmp';await fs.writeFile(temp,JSON.stringify(manifest,null,2)+'\n');await fs.rename(temp,manifestPath);return result;
}
