#!/usr/bin/env node
import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {readConfig,loadLayers,inferConfig,merge} from '../config/index.mjs';import {build,approveCheckpoint} from '../runtime/application.mjs';import {doctor} from '../runtime/doctor.mjs';import {skillRegistry} from '../runtime/skills.mjs';import {resolveTemplate} from '../runtime/template.mjs';import {reviewPptx,learnCandidate,promoteCandidate,rejectCandidate} from '../review/index.mjs';import {compareAndRecord,explicitFeedback,preferenceCandidates,confirmFeedback} from '../feedback/index.mjs';import {createSkill} from '../feedback/skill-builder.mjs';import {health,retrieveContext,selectPacks} from '../../engine/knowledge/index.mjs';import {localDashboard} from '../quality/dashboard.mjs';import {ingestCandidate} from '../knowledge/ingest.mjs';import {recordDecision} from '../knowledge/decision.mjs';import {learnDirectory,resolveLearningLibrary} from '../knowledge/incremental-learn.mjs';import {assetsOnly} from '../runtime/assets.mjs';import {partialRebuild,latestProject} from '../runtime/partial-rebuild.mjs';
import {askGenerationOptions,discoverLocalInputs} from './generation-options.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
export async function cli(argv,write=console.log){const [command='help',...rest]=argv;const opts={},position=[];for(let i=0;i<rest.length;i++){if(rest[i].startsWith('--')){opts[rest[i].slice(2)]=rest[i+1]?.startsWith('--')||!rest[i+1]?true:rest[++i];}else position.push(rest[i]);}
  if(command==='help'||opts.help){write('CPGHBPPT\n./CPGHBPPT init | doctor | learn [目录] | build [brief.md|presentation.yaml] [--source-mode local|web|hybrid] [--images yes|no] | research | outline | assets <project-id> | review <pptx|project-id> | improve <project-id> <page> --spec slide.json | rebuild <page> [--project id --spec slide.json] | update <project-id> <page> --spec slide.json | source <project-id> [page] | qa | status | skills | templates');return;}
  if(command==='assets'){if(!position[0])throw new Error('用法：./CPGHBPPT assets <已有 Research 项目 ID>');const result=await assetsOnly(root,position[0]);write(`Visual Research：已发现 ${result.coverage.found}/${result.coverage.required} 个槽位，内部可用 ${result.coverage.usable}，缺口 ${result.coverage.missing.join(', ')||'无'}。Manifest：${result.manifest_path}`);return result;}
  if(command==='rebuild'){let id=opts.project,page;if(position.length>=2){id=position[0];page=Number(position[1]);}else page=Number(position[0]);if(!Number.isInteger(page))throw new Error('用法：./CPGHBPPT rebuild <page> --project <project-id> [--spec slide.json]');id=id??await latestProject(root);const result=await partialRebuild(root,id,page,{specFile:opts.spec});write(`局部重建完成：${id} 第 ${page} 页\nPPTX：${result.output}\n其他 ${result.isolation.other_slide_count} 页 XML 哈希保持不变\nQA：${result.qa.passed?'通过':'未通过'}\n隔离检查：${result.isolation.status}`);return result;}
  if(command==='update'||command==='improve'){if(!position[0]||!Number.isInteger(Number(position[1]))||!opts.spec)throw new Error(`用法：./CPGHBPPT ${command} <project-id> <page> --spec <已审阅的-slide-spec.json>`);const result=await partialRebuild(root,position[0],Number(position[1]),{specFile:opts.spec});write(`${command==='update'?'定向更新':'改进稿'}完成：${result.output}\n其他 ${result.isolation.other_slide_count} 页 XML 哈希保持不变；QA ${result.qa.passed?'通过':'未通过'}。`);return result;}
  if(command==='source'){if(!position[0])throw new Error('用法：./CPGHBPPT source <project-id> [page]');const dir=path.join(root,'projects',position[0]),manifest=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8')),specs=JSON.parse(await fs.readFile(path.join(dir,'artifacts/slide-specs.json'),'utf8')),page=position[1]?Number(position[1]):null;if(page&&(!Number.isInteger(page)||page<1||page>specs.length))throw new Error(`页码超出范围（共 ${specs.length} 页）。`);const selected=page?[specs[page-1]]:specs;const result={project_id:position[0],appendix:manifest.outputs?.sources??null,slides:selected.map((s,i)=>({page:page??i+1,slide_id:s.slide_id,title:s.title,sources:s.sources??[],source_labels:s.render_options?.source_labels??[],source_urls:s.render_options?.source_urls??[]}))};write(JSON.stringify(result,null,2));return result;}
  if(command==='doctor'){for(const x of await doctor(root))write(`${x.status==='ok'?'✓':'⚠'} ${x.name}: ${x.detail}`);return;}
  if(command==='review'){if(!position[0])throw new Error('用法：./CPGHBPPT review <已有 PPTX 或项目 ID>');let target=path.resolve(position[0]);if(!await fs.access(target).then(()=>true,()=>false)){const m=JSON.parse(await fs.readFile(path.join(root,'projects',position[0],'manifest.json'),'utf8'));target=m.outputs?.pptx;}const result=await reviewPptx(root,target);write(`只读评审：${result.slide_count} 页；${result.report.issues.length} 项文本规则提示。结果：${result.output}。视觉和事实来源未核验。`);return result;}
  if(command==='learn'){const target=position[0]?path.resolve(position[0]):await resolveLearningLibrary(root);const stat=await fs.stat(target);if(stat.isDirectory()){const result=await learnDirectory(root,target,{manifestPath:opts.manifest?path.resolve(opts.manifest):path.join(root,'workspace/learning-manifest.json')});write(`增量学习：发现 ${result.discovered}，新增/变更 ${result.learned.length}，未变化跳过 ${result.skipped.length}，失败 ${result.failed.length}，锁文件忽略 ${result.ignored.length}。清单：${result.manifest_path}`);if(result.failed.length)write(`需处理：${result.failed.map(x=>path.basename(x.file)+': '+x.error).join('；')}`);return result;}const result=await learnCandidate(root,target,{scope:opts.scope??'presentation-pattern'});write(`已生成候选 ${result.candidate.id}：${result.output}。未进入长期知识；请审阅后显式运行 ./CPGHBPPT knowledge promote ... --confirm --reviewer ... --reason ... --scope ...。`);return result;}
  if(command==='knowledge'){const sub=position[0];if(sub==='decision'){if(position[1]!=='add')throw new Error('用法：./CPGHBPPT knowledge decision add --statement ... --scope ... --source 本地文件 --reviewer ... --reason ... --date YYYY-MM-DD --confirm');const output=await recordDecision(root,{statement:opts.statement,scope:opts.scope,source:opts.source,reviewer:opts.reviewer,reason:opts.reason,decision_date:opts.date,confirm:!!opts.confirm,valid_until:opts['valid-until']??null});write(`已保存限定范围的历史决策（不视为当前事实）：${output}`);return output;}if(sub==='ingest'){if(!position[1])throw new Error('用法：./CPGHBPPT knowledge ingest <本地文件>');const result=await ingestCandidate(root,position[1],{scope:opts.scope??'unreviewed-source'});write(`已提取候选 ${result.candidate.id}（仅结构，不保存正文）：${result.output}；需人工审阅。`);return result;}if(sub==='health'){const report=await health(root);const output=path.join(root,'knowledge-base/knowledge-health-report.json');await fs.writeFile(output,JSON.stringify(report,null,2));write(JSON.stringify({...report,output},null,2));return report;}
    if(sub==='search'){const config=inferConfig(position.slice(1).join(' ')||opts.topic||'产品');const data=await retrieveContext(root,config);write(JSON.stringify(data,null,2));return data;}
    if(sub==='reject'){const output=await rejectCandidate(root,position[1],{confirm:!!opts.confirm,reviewer:opts.reviewer,reason:opts.reason});write(`已拒绝候选并保留审计记录：${output}`);return output;}if(sub==='promote'){const output=await promoteCandidate(root,position[1],{confirm:!!opts.confirm,reviewer:opts.reviewer,reason:opts.reason,scope:opts.scope});write(`已人工确认并保存为低可信、限定范围的结构知识：${output}`);return output;}
    throw new Error('用法：./CPGHBPPT knowledge <health|search 查询|promote id --confirm --reviewer 姓名 --reason 理由 --scope 范围>');}
  if(command==='feedback'){const sub=position[0];if(sub==='diff'){const result=await compareAndRecord(root,position[1],path.resolve(position[2]));write(`检测到 ${result.signals.length} 项修改，均标记 UNCLASSIFIED 待人工判断：${result.output}`);return result;}
    if(sub==='add'){const result=await explicitFeedback(root,{project_id:position[1],slide_id:opts.slide??null,category:opts.category??'content',signal_class:opts.class??'UNCLASSIFIED',original:opts.original??null,updated:opts.updated??null,comment:opts.comment??''});write(`反馈已记录（待复核，不自动更新知识）：${result.output}`);return result;}
    if(sub==='confirm'){const result=await confirmFeedback(root,position[1],position[2],{signal_class:opts.class,reason:opts.reason});write(`已复核 ${result.feedback_id} 为 ${result.signal_class}；单次反馈不会自动进入长期知识。`);return result;}
    if(sub==='preferences'){const x=await preferenceCandidates(root);write(JSON.stringify(x,null,2));return x;}
    throw new Error('用法：./CPGHBPPT feedback <diff project edited.json | add project --category ... --class ... --comment ... | preferences>');}
  if(command==='skill'){if(position[0]!=='create'||!position[1])throw new Error('用法：./CPGHBPPT skill create <name>');const dir=await createSkill(root,position[1]);write(`Draft Skill（默认禁用，完成测试后再启用）：${dir}`);return dir;}
  if(command==='dashboard'){const d=await localDashboard(root);write(JSON.stringify(d,null,2));return d;}
  if(command==='skills'){const s=await skillRegistry(root);write(`${s.length} Skills\n`+s.map(x=>`- ${x.category}/${x.id} v${x.version}`).join('\n'));return;}
  if(command==='templates'){const r=JSON.parse(await fs.readFile(path.join(root,'templates/registry.json'),'utf8'));for(const t of r.templates){let status;try{status=(await resolveTemplate(root,t.id)).manifest.version}catch(e){status=e.message}write(`${t.id}: ${status}`);}return;}
  if(command==='init'){const workspaceLink=path.join(root,'workspace');for(const dir of ['input','旧PPT库','projects','personal-knowledge','personal-patterns','config'])await fs.mkdir(path.join(workspaceLink,dir),{recursive:true});const workspace=await fs.realpath(workspaceLink).catch(()=>workspaceLink),file=path.join(workspace,'config/presentation.yaml');let created=false;await fs.access(file).catch(async e=>{if(e.code!=='ENOENT')throw e;await fs.copyFile(path.join(root,'examples/01-product-overview/project.yaml'),file);created=true;});write(`${created?'已创建':'已保留'}个人工作区：${workspace}\n配置：${file}\n把资料放入 workspace/input/，优秀历史 PPT 放入 workspace/旧PPT库/。下一步运行 ./CPGHBPPT doctor。`);return;}
  if(['build','research','outline','render'].includes(command)){
    let config;const file=position[0];if(command==='render'){if(!file)throw new Error('请指定项目 ID');const m=JSON.parse(await fs.readFile(path.join(root,'projects',file,'manifest.json'),'utf8'));config=m.config;}else if(file&&/\.(?:ya?ml|json)$/.test(file)){config=await loadLayers(root,path.resolve(file));const dir=path.dirname(path.resolve(file));config.input_files=(config.input_files??[]).map(f=>path.resolve(dir,f));}else{let text;if(file&&/\.(?:md|txt)$/.test(file)){text=await fs.readFile(file,'utf8')}else text=opts.topic??position.join(' ');if(!text)throw new Error('请输入 brief.md、project.yaml 或 --topic。');const inputs=file&&/\.(?:md|txt)$/.test(file)?[path.resolve(file)]:[];if(opts.input)inputs.push(path.resolve(opts.input));
      const explicitSource=opts['source-mode']??opts.source,explicitImages=opts.images??(opts['no-images']?'no':null);const choices=await askGenerationOptions({sourceMode:explicitSource,images:explicitImages});
      if(['local','hybrid'].includes(choices.sourceMode)&&!inputs.length)inputs.push(...await discoverLocalInputs(root));
      config=merge(await loadLayers(root),inferConfig(text,inputs));config.research.source_mode=choices.sourceMode;config.research.enabled=choices.sourceMode!=='local';config.visual={...(config.visual??{}),enabled:choices.images,acquisition:'screenshot'};if(opts.type)config.presentation.type=opts.type;}
    config.project.id=opts.project??config.project.id;if(opts['no-research'])config.research.enabled=false;if(opts['no-pptx'])config.output.pptx=false;if(opts.verbose)config.runtime.verbose=true;if(opts['no-domain'])config.runtime.domain_packs=false;
    const p=await build(root,config,{mode:command==='render'?'build':command,verbose:!!opts.verbose,approve:!!opts.approve});write(`CPGHBPPT · ${p.id}\n状态：${p.manifest.status}\n流程：${p.manifest.workflow_stages.join(' → ')}`);if(p.manifest.checkpoint)write(`等待确认：${p.manifest.checkpoint}。运行 ./CPGHBPPT approve ${p.id} ${p.manifest.checkpoint}，再运行 ./CPGHBPPT build presentation.yaml。`);if(p.manifest.limitations?.length)write(`限制：${p.manifest.limitations.join('；')}`);if(p.manifest.outputs.pptx)write(`PPTX：${p.manifest.outputs.pptx}\n来源：${p.manifest.outputs.sources}\n预览：${p.manifest.outputs.preview}\nQA：${p.manifest.qa?.passed?'通过':'待检查'}`);else write(`项目目录：${p.dir}`);return p;}
  if(command==='status'||command==='qa'){if(!position[0])throw new Error('请指定项目 ID');const p=path.join(root,'projects',position[0]);const m=JSON.parse(await fs.readFile(path.join(p,'manifest.json'),'utf8'));if(command==='status')write(JSON.stringify({id:m.project_id,status:m.status,checkpoint:m.checkpoint,stages:m.stages,outputs:m.outputs},null,2));else{const report=JSON.parse(await fs.readFile(path.join(p,'artifacts/render/qa-report.json'),'utf8'));write(JSON.stringify(report.summary,null,2));}return;}
  if(command==='approve'){if(!position[0]||!position[1])throw new Error('用法：./CPGHBPPT approve <project-id> <checkpoint>');const m=await approveCheckpoint(root,position[0],position[1]);write(`${m.project_id}：${position[1]} 已确认；重新运行 build 可继续。`);return;}
  throw new Error('未知命令：'+command);
}
const isMain=process.argv[1]&&await fs.realpath(process.argv[1]).then(p=>p===fileURLToPath(import.meta.url)).catch(()=>false);
if(isMain){cli(process.argv.slice(2)).catch(async e=>{const logfile=path.join(root,'projects','last-error.log');await fs.writeFile(logfile,`${new Date().toISOString()} ${e.stack}\n`).catch(()=>{});const message=e.code==='ENOENT'&&e.path?`未找到输入文件或配置：${e.path}。请检查路径。`:e.message;console.error('无法完成：'+message);if(process.argv.includes('--verbose'))console.error(e.stack);process.exitCode=1;});}
