import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';
const digest=x=>createHash('sha256').update(x??'').digest('hex').slice(0,16);
const categories=new Set(['content','storyline','analysis','layout','visual','data','source','tone']);
const classes=new Set(['UNCLASSIFIED','PREFERENCE','QUALITY_CORRECTION','BUSINESS_DECISION','ONE_OFF_CHANGE','STYLE_CHANGE']);
const redact=x=>x==null?null:String(x).replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,'[EMAIL]').replace(/\b\+?\d[\d -]{9,}\b/g,'[NUMBER]').slice(0,220);
export function diffSlides(projectId,before,after){const next=new Map(after.map(s=>[s.slide_id,s])),out=[];for(const s of before){const n=next.get(s.slide_id);if(!n){out.push({slide_id:s.slide_id,feedback_type:'slide_deleted',category:'storyline',original:s.title,updated:null});continue;}if(n.title!==s.title)out.push({slide_id:s.slide_id,feedback_type:'title_edit',category:'content',original:s.title,updated:n.title});if(n.layout?.layout_id!==s.layout?.layout_id)out.push({slide_id:s.slide_id,feedback_type:'layout_change',category:'layout',original:s.layout?.layout_id,updated:n.layout?.layout_id});if(n.visualization?.type!==s.visualization?.type)out.push({slide_id:s.slide_id,feedback_type:'other_edit',category:'visual',original:s.visualization?.type,updated:n.visualization?.type});const oldBrands=(s.content?.structured_data?.competitors??[]).map(x=>x.name).join(',');const newBrands=(n.content?.structured_data?.competitors??[]).map(x=>x.name).join(',');if(oldBrands!==newBrands)out.push({slide_id:s.slide_id,feedback_type:'other_edit',category:'analysis',original:oldBrands,updated:newBrands});}return out.map((x,i)=>({...x,feedback_id:`fb-${digest(projectId+Date.now()+i+x.feedback_type)}`,project_id:projectId,signal_class:'UNCLASSIFIED',original:redact(x.original),updated:redact(x.updated),comment:'检测到差异；不能自动判断修改原因。',timestamp:new Date().toISOString(),status:'pending_review',suggested_classes:x.feedback_type==='slide_deleted'?['ONE_OFF_CHANGE','QUALITY_CORRECTION']:x.feedback_type==='layout_change'?['PREFERENCE','QUALITY_CORRECTION','ONE_OFF_CHANGE']:['QUALITY_CORRECTION','STYLE_CHANGE','PREFERENCE'],classification_note:'原因仅能由修改者复核；建议类别不是结论。'}));}
export async function recordFeedback(root,projectId,items){const dir=path.join(root,'projects',projectId,'feedback');await fs.mkdir(dir,{recursive:true});const output=path.join(dir,'signals.jsonl');for(const x of items){if(!categories.has(x.category)||!classes.has(x.signal_class))throw new Error('Invalid feedback category/class');await fs.appendFile(output,JSON.stringify(x)+'\n');}return output;}
export async function compareAndRecord(root,projectId,editedFile){const orig=JSON.parse(await fs.readFile(path.join(root,'projects',projectId,'artifacts/slide-specs.json'),'utf8'));const after=JSON.parse(await fs.readFile(editedFile,'utf8'));if(!Array.isArray(after)||new Set(after.map(x=>x.slide_id)).size!==after.length)throw new Error('Edited Slide Spec needs unique slide IDs');const result=diffSlides(projectId,orig,after);const output=await recordFeedback(root,projectId,result);return {output,signals:result};}
export async function explicitFeedback(root,{project_id,slide_id=null,category='content',signal_class='UNCLASSIFIED',original=null,updated=null,comment=''}){if(!categories.has(category)||!classes.has(signal_class))throw new Error('Invalid feedback category/class');const entry={feedback_id:'fb-'+digest(project_id+Date.now()+Math.random()),project_id,slide_id,feedback_type:'explicit',category,signal_class,original:redact(original),updated:redact(updated),comment:redact(comment)||'',timestamp:new Date().toISOString(),status:'pending_review'};return {entry,output:await recordFeedback(root,project_id,[entry])};}
export async function preferenceCandidates(root){const dir=path.join(root,'projects'),groups=new Map();for(const id of await fs.readdir(dir)){const file=path.join(dir,id,'feedback/signals.jsonl');let rows;try{rows=(await fs.readFile(file,'utf8')).trim().split('\n').map(JSON.parse)}catch{continue}for(const x of rows){if(x.signal_class!=='PREFERENCE'||x.status!=='confirmed'||['source','data'].includes(x.category))continue;const key=`${x.category}:${x.original??''}=>${x.updated??''}`;const g=groups.get(key)??new Set();g.add(id);groups.set(key,g);}}
return [...groups.entries()].filter(([,projects])=>projects.size>=3).map(([key,projects])=>({key,distinct_projects:projects.size,status:'candidate_only',rule:'Manual team review required; never overrides evidence/brand/QA'}));}
export async function confirmFeedback(root,projectId,id,{signal_class,reason}={}){if(!classes.has(signal_class)||signal_class==='UNCLASSIFIED'||!reason?.trim())throw new Error('必须填写明确分类和复核原因');const file=path.join(root,'projects',projectId,'feedback/signals.jsonl');const rows=(await fs.readFile(file,'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse);const item=rows.find(x=>x.feedback_id===id);if(!item)throw new Error('反馈 ID 不存在');if(item.status!=='pending_review')throw new Error('此反馈已经复核');item.status='confirmed';item.signal_class=signal_class;item.comment=`${item.comment} | 复核：${redact(reason)}`;const temp=file+'.tmp';await fs.writeFile(temp,rows.map(x=>JSON.stringify(x)).join('\n')+'\n');await fs.rename(temp,file);return item;}
