import fs from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import sharp from 'sharp';import {createHash} from 'node:crypto';
import {safeFetch,safeUrl,authority} from '../../source/index.mjs';import {visualHash} from '../deduplication/index.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
async function viaCurl(url){await safeUrl(url);return await new Promise((resolve,reject)=>{const child=spawn('curl',['-fsS','--max-time','15','--max-redirs','0','--proto','=https','--max-filesize','15000000',url],{stdio:['ignore','pipe','pipe']});const chunks=[];let size=0,err='';child.stdout.on('data',b=>{size+=b.length;if(size>15_000_000){child.kill();return;}chunks.push(b)});child.stderr.on('data',b=>err+=b);child.on('close',code=>code===0&&size<=15_000_000?resolve(Buffer.concat(chunks)):reject(new Error(`curl failed ${code}: ${err.slice(0,130)}`)));child.on('error',reject)});}
export function canonicalAssetUrl(candidate){const u=new URL(candidate.url);if(u.hostname==='static.wixstatic.com'&&u.pathname.includes('/v1/'))return {url:u.origin+u.pathname.split('/v1/')[0],derivation:'official page referenced Wix variant; original asset base derived from same media ID'};return {url:candidate.url,derivation:null};}
export async function downloadCandidate(candidate,page,{dir,source_id,entity,asset_type,related_evidence=[],maxBytes=15_000_000}={}){
 if(authority(page.url)!=='A')throw new Error('Image page is not an official source');if(!page.html?.includes(candidate.url))throw new Error('Image candidate not referenced in verified official HTML');const normalized=canonicalAssetUrl(candidate);await safeUrl(normalized.url);
 let bytes;try{const {response}=await safeFetch(normalized.url);if(!response.ok)throw new Error('HTTP '+response.status);if(Number(response.headers.get('content-length')||0)>maxBytes)throw new Error('asset too large');bytes=Buffer.from(await response.arrayBuffer());}catch(error){bytes=await viaCurl(normalized.url);}if(bytes.length>maxBytes)throw new Error('asset too large');const meta=await sharp(bytes,{limitInputPixels:80_000_000}).metadata();if(!meta.width||!meta.height)throw new Error('INVALID_IMAGE');if(meta.format==='svg')throw new Error('SVG requires separate sanitization/manual review');const extension={jpeg:'jpg',png:'png',webp:'webp',gif:'gif',avif:'avif'}[meta.format];if(!extension)throw new Error(`Unsupported image format: ${meta.format}`);const digest=hash(bytes),filename=digest.slice(0,20)+'.'+extension;await fs.mkdir(dir,{recursive:true});const local=path.join(dir,filename);await fs.writeFile(local,bytes);const phash=await visualHash(bytes);return {asset_id:'A'+digest.slice(0,12),type:asset_type==='feature_image'?'diagram':asset_type==='feature_screenshot'?'website_screenshot':asset_type,asset_type,brand:entity,entity,entities:[entity],product:'',source_url:normalized.url,source_page_url:page.url,source_id,local_path:path.resolve(local),format:extension,width:meta.width,height:meta.height,has_transparency:!!meta.hasAlpha,usage:'internal research review only',license_notes:'Official-page-linked visual. Reuse rights unverified; do not externally publish without clearance.',status:Math.min(meta.width,meta.height)<400?'LOW_RESOLUTION':'review_required',content_hash:digest,perceptual_hash:phash,related_evidence,related_claims:[],related_slides:[],semantic_description:candidate.alt||'',visual_content:[],semantic_review:'pending',visual_role:asset_type==='product_image'?'CONTEXT_VISUAL':'EVIDENCE_VISUAL',quality:{authority:'official_page_linked',resolution:Math.min(meta.width,meta.height)<400?'low':'adequate',visual_clarity:'not_assessed',watermark:'not_assessed',text_density:'not_assessed',aspect_ratio:meta.width/meta.height,contextual_relevance:candidate.contextual_relevance??null,rank_score:candidate.rank_score??null},source:{page_url:page.url,page_title:page.title,asset_url:normalized.url,source_id,origin:candidate.origin,derivation:normalized.derivation,accessed_at:new Date().toISOString()},rights:{status:'unverified',scope:'internal_review'},used:false};
}
