#!/usr/bin/env node
// Local-only MCP stdio interface. Business logic is delegated to the Application Layer.
import readline from 'node:readline';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {build} from '../runtime/application.mjs';import {project,save} from '../runtime/project.mjs';import {inferConfig,loadLayers,merge} from '../config/index.mjs';import {planResearch} from '../../engine/research/planner/index.mjs';import {skillRegistry} from '../runtime/skills.mjs';import {reviewPptx,learnCandidate} from '../review/index.mjs';import {retrieveContext,health} from '../../engine/knowledge/index.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const J={type:'object',properties:{brief:{type:'string'},project_id:{type:'string'},config:{type:'object'},file:{type:'string'}}};const names=['create_project','analyze_brief','plan_research','run_research','build_storyline','build_deck','render_deck','run_qa','get_project_status','get_output','list_skills','list_templates','review_presentation','learn_candidate','retrieve_domain_context','knowledge_health'];
const tools=names.map(name=>({name,description:`Product PPT Agent ${name} via local Application Layer; no implicit upload.`,inputSchema:J}));
const send=obj=>process.stdout.write(JSON.stringify({jsonrpc:'2.0',...obj})+'\n');
async function call(name,args={}){if(name==='review_presentation'){if(!args.file)throw new Error('file required');const x=await reviewPptx(root,args.file);return {output:x.output,issues:x.report.issues,limitations:x.report.notes};}if(name==='learn_candidate'){if(!args.file)throw new Error('file required');const x=await learnCandidate(root,args.file);return {candidate_id:x.candidate.id,status:x.candidate.status,output:x.output,requires_human_review:true};}if(name==='knowledge_health')return await health(root);if(name==='retrieve_domain_context'){const q=args.config??inferConfig(args.brief??'产品');return await retrieveContext(root,q);}if(name==='list_skills')return await skillRegistry(root);if(name==='list_templates')return JSON.parse(await fs.readFile(path.join(root,'templates/registry.json'),'utf8')).templates;
  let cfg=args.config??(args.brief?merge(await loadLayers(root),inferConfig(args.brief)):null);if(args.project_id&&!cfg){const m=JSON.parse(await fs.readFile(path.join(root,'projects',args.project_id,'manifest.json'),'utf8'));cfg=m.config;}
  if(name==='analyze_brief')return cfg??{error:'brief or config required'};
  if(name==='plan_research'){if(!cfg)throw new Error('brief or config required');return planResearch({brands:cfg.research?.competitors??[]});}
  if(name==='create_project'){if(!cfg)throw new Error('brief or config required');const p=await project(root,cfg);await save(p);return {project_id:p.id,workspace:p.dir};}
  if(name==='get_project_status'||name==='get_output'||name==='run_qa'){if(!args.project_id)throw new Error('project_id required');const m=JSON.parse(await fs.readFile(path.join(root,'projects',args.project_id,'manifest.json'),'utf8'));if(name==='get_project_status')return {status:m.status,stages:m.stages,checkpoint:m.checkpoint};if(name==='get_output')return m.outputs;return JSON.parse(await fs.readFile(path.join(root,'projects',args.project_id,'artifacts/render/qa-report.json'),'utf8')).summary;}
  if(!cfg)throw new Error('brief or config required');if(args.project_id)cfg.project.id=args.project_id;const mode=name==='run_research'?'research':name==='build_storyline'?'outline':'build';const p=await build(root,cfg,{mode});return {project_id:p.id,status:p.manifest.status,outputs:p.manifest.outputs,checkpoint:p.manifest.checkpoint};}
const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of rl){let req;try{req=JSON.parse(line);if(req.method==='notifications/initialized')continue;if(req.method==='initialize'){send({id:req.id,result:{protocolVersion:req.params?.protocolVersion??'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'cpghbppt',version:'0.5.0'}}});continue;}if(req.method==='ping'){send({id:req.id,result:{}});continue;}if(req.method==='tools/list'){send({id:req.id,result:{tools}});continue;}if(req.method==='tools/call'){if(!names.includes(req.params?.name))throw new Error('Unknown tool');const result=await call(req.params.name,req.params.arguments);send({id:req.id,result:{content:[{type:'text',text:JSON.stringify(result)}]}});continue;}if(req.id!==undefined)send({id:req.id,error:{code:-32601,message:'Method not found'}});}catch(e){if(req?.id!==undefined)send({id:req.id,error:{code:-32000,message:e.message}});else console.error(e.message);}}
