import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {parseYaml} from '../../app/config/yaml.mjs';import {inferConfig,merge,validateConfig,readConfig} from '../../app/config/index.mjs';import {workflow} from '../../app/workflows/index.mjs';import {discoverSkills} from '../../app/runtime/skills.mjs';import {stage,project} from '../../app/runtime/project.mjs';import {readInputs} from '../../app/runtime/input.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
test('YAML/project config and override order',async()=>{const c=await readConfig(path.join(root,'examples/01-product-overview/project.yaml'));assert.deepEqual(c.research.competitors,['Samsung','Sony','Hisense']);assert.equal(validateConfig(merge({research:{enabled:false}},c)).research.enabled,true);assert.throws(()=>parseYaml('a: 1\na: 2'),/Duplicate/);assert.throws(()=>parseYaml('a: !unsafe'),/aliases\/tags/);});
test('intent and stage toggles stay separate',async()=>{const c=inferConfig('/ppt 不要 Research，不要修改内容，只按照公司模板做 PPT',['input/content.md']);assert.equal(c.research.enabled,false);assert.equal(c.reasoning.content_rewrite,false);assert.equal(c.presentation.type,'product-overview');const w=await workflow(root,c);assert.equal(w.stages.includes('RESEARCHING'),false);assert.equal(w.stages.includes('RENDERING'),true);const r=inferConfig('分析 Samsung Sony Hisense 的 AI Picture 竞品');assert.equal(r.presentation.type,'competitor-analysis');assert.deepEqual(r.research.competitors,['Samsung','Sony','Hisense']);});
test('skill discovery picks up custom skill without core changes',async()=>{const skills=await discoverSkills(root);assert.ok(skills.length>=41);assert.equal(skills.find(x=>x.id==='tv-picture-quality').version,'1.0.0');});
test('stage cache resumes and invalidates on input change',async()=>{const temp=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-app-'));try{const p=await project(temp,{project:{name:'Sample'},template:{id:'tcl-product'},presentation:{type:'user-insight'}});const f=path.join(p.dir,'artifacts/result.txt');let calls=0;await stage(p,'RENDERING','one',[f],async()=>{calls++;await fs.writeFile(f,'v1')});await stage(p,'RENDERING','one',[f],async()=>{calls++;});assert.equal(calls,1);await stage(p,'RENDERING','two',[f],async()=>{calls++;await fs.writeFile(f,'v2')});assert.equal(calls,2);}finally{await fs.rm(temp,{recursive:true,force:true})}});
test('local synthetic PDF is text-readable and not uploaded',async()=>{const [input]=await readInputs([path.join(root,'examples/03-user-insight/input/NPS.pdf')]);assert.match(input.text,/SYNTHETIC NPS TEST FIXTURE/);assert.match(input.text,/not a real NPS report/);});
test('MCP stdio exposes app-level tools',async()=>{const child=spawn(process.execPath,[path.join(root,'app/adapters/mcp-stdio.mjs')],{cwd:root});const outputs=[];child.stdout.on('data',b=>outputs.push(b.toString()));child.stdin.write('{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}\n');child.stdin.write('{"jsonrpc":"2.0","id":2,"method":"tools/list"}\n');child.stdin.end();await new Promise((resolve,reject)=>{child.once('close',code=>code===0?resolve():reject(new Error('MCP exit '+code)));child.once('error',reject)});const lines=outputs.join('').trim().split('\n').map(JSON.parse);assert.equal(lines[0].result.serverInfo.name,'product-ppt-agent');assert.ok(lines[1].result.tools.some(t=>t.name==='build_deck'));});
