import fs from 'node:fs/promises';import path from 'node:path';
const terms=s=>new Set(String(s).toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>1));
const within=(root,p)=>{const abs=path.resolve(root,p);if(!abs.startsWith(path.resolve(root)+path.sep))throw new Error('Knowledge path escapes project root');return abs;};
export async function selectPacks(root,text,{enabled=true}={}){if(!enabled)return [];const ids=['tv-picture-quality','ai-tv','product-management'];const packs=[];for(const id of ids){const m=JSON.parse(await fs.readFile(path.join(root,'domain-packs',id,'manifest.json'),'utf8'));if(id==='product-management'||m.match.some(x=>text.toLowerCase().includes(x.toLowerCase())))packs.push(m);}return packs;}
export function chooseDimensions(packs,topic){const t=topic.toLowerCase();const key=/ai\s*picture|智能画质|aipq/.test(t)?'ai-picture':/mini\s*led/.test(t)?'mini-led':/校准|calibration/.test(t)?'calibration':/lcd/.test(t)?'lcd':'default';return {topic:key,dimensions:[...new Set(packs.flatMap(p=>p.dimension_rules[key]??(p.id==='product-management'?p.dimension_rules.default:[])))].slice(0,10)};}
export async function approvedItems(root){const directories=['projects','decisions','patterns','best-practices','department','methodologies'];const all=[];for(const d of directories){const dir=path.join(root,'knowledge-base',d);let names=[];try{names=await fs.readdir(dir)}catch(e){if(e.code!=='ENOENT')throw e}for(const name of names){if(!name.endsWith('.json'))continue;try{const x=JSON.parse(await fs.readFile(path.join(dir,name),'utf8'));if(x.id&&x.status==='approved')all.push(x);}catch{}}}return all;}
export function isStale(item,now=Date.now()){if(item.valid_until&&Date.parse(item.valid_until)<now)return true;const tags=new Set(item.tags??[]);const ttl=tags.has('price')?1:tags.has('product-spec')||tags.has('ai-capability')?30:tags.has('market-share')?365:null;return ttl!==null&&now-Date.parse(item.last_updated)>ttl*864e5;}
export function rankItems(items,query,{limit=5,now=Date.parse(new Date().toISOString().slice(0,10)+'T00:00:00Z')}={}){const q=terms(query);return items.filter(x=>x.status==='approved').map(item=>{const t=terms([item.statement,item.scope,...(item.tags??[]),item.domain].join(' '));let overlap=[...q].filter(v=>t.has(v)).length;const expired=isStale(item,now);const age=Math.max(0,(now-Date.parse(item.last_updated||0))/864e5);const status=item.status==='approved'?5:0,confidence={high:4,medium:2,low:0}[item.confidence]??0;const score=overlap*6+status+confidence+Math.max(0,2-age/365)-(expired?100:0);return {...item,retrieval_score:score,topic_overlap:overlap,expired:!!expired};}).filter(x=>!x.expired&&x.topic_overlap>0).sort((a,b)=>b.retrieval_score-a.retrieval_score).slice(0,limit);}
export async function retrieveContext(root,config,{enabled=true}={}){const topic=[config.project?.name,config.presentation?.brief,config.presentation?.purpose].filter(Boolean).join(' ');const packs=await selectPacks(root,topic,{enabled}),selection=chooseDimensions(packs,topic),matched=rankItems(await approvedItems(root),topic);const references=[];for(const p of packs)for(const file of p.knowledge??[]){const text=await fs.readFile(within(root,file),'utf8');references.push({pack_id:p.id,path:file,status:p.status,usage:'question_framework_not_fact',snippet:text.slice(0,700)});}
const catalog=JSON.parse(await fs.readFile(path.join(root,'knowledge/patterns/catalog.json'),'utf8'));const patternHints=[];for(const entry of catalog.patterns){if(/竞品|competitor/i.test(topic)&&!entry.pattern_id.includes('COMPETITOR')&&entry.pattern_id!=='EVIDENCE_TO_CONCLUSION')continue;const p=JSON.parse(await fs.readFile(within(root,path.join('knowledge/patterns',entry.path)),'utf8'));patternHints.push({id:p.pattern_id,maturity:p.maturity,structure:p.structure,when_to_use:p.when_to_use,when_not_to_use:p.when_not_to_use,safe_to_apply:false,reason:'Existing Pattern is still a candidate; check evidence and constraints before using; source PPT not imported.'});if(patternHints.length>=2)break;}
const glossary=JSON.parse(await fs.readFile(path.join(root,'knowledge-base/glossary/terms.json'),'utf8'));const search=[topic,selection.dimensions.join(' ')].join(' ').toLowerCase();const terminology=glossary.terms.filter(x=>[x.name,...x.aliases].some(t=>search.includes(t.toLowerCase()))).slice(0,6).map(x=>({name:x.name,definition:x.definition,usage:x.presentation_usage,status:'method_reference',source_url:x.source_url}));return {topic:selection.topic,terminology,pattern_hints:patternHints,packs:packs.map(p=>({id:p.id,version:p.version,status:p.status,skills:p.skills,qa_rules:p.qa_rules})),dimensions:selection.dimensions,references:references.slice(0,8),approved_knowledge:matched.map(x=>({id:x.id,statement:x.statement,scope:x.scope,source:x.source,last_updated:x.last_updated,confidence:x.confidence,retrieval_score:x.retrieval_score})),rules:['Candidate domain methods are questions, not external facts','Historical decisions require current revalidation','Never override brand or evidence rules']};}
export async function health(root,{now=Date.now()}={}){const items=await approvedItems(root);const stale=items.filter(x=>isStale(x,now)).map(x=>x.id);const byHash=new Map(),duplicates=[];for(const x of items){const key=x.statement.trim().toLowerCase();if(byHash.has(key))duplicates.push([byHash.get(key),x.id]);else byHash.set(key,x.id);}return {generated_at:new Date(now).toISOString(),approved_count:items.length,stale,duplicates,conflicts:[],notes:['Qualitative contradiction detection requires human review.','Candidate and rejected items are not retrieved as facts.']};}
